"use client";

import { useEffect, useState } from "react";
import type { BusinessDetail } from "../../../lib/studio/business/contracts";
import { asBusinessError, readBusinessOptions, safeBusinessUrl, type BusinessOption, type BusinessOptionKind } from "../../../lib/studio/business/client";
import { Badge, Empty, dateLabel, label, memberName, type Members, type MutationController } from "./ui";
import styles from "./business.module.css";

function LinkSelector({ workspaceId, kind, selected, disabled, onSelect, excludeId }: { workspaceId: string; kind: BusinessOptionKind; selected: string; disabled: boolean; onSelect: (option: BusinessOption | null) => void; excludeId?: string }) {
  const [query, setQuery] = useState("");
  const [options, setOptions] = useState<BusinessOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [attempt, setAttempt] = useState(0);
  useEffect(() => {
    const controller = new AbortController();
    setLoading(true); setError("");
    const timer = window.setTimeout(() => { void readBusinessOptions(workspaceId, kind, query, controller.signal).then(result => { if (!controller.signal.aborted) setOptions(result.filter(option => option.id !== excludeId)); }).catch(cause => { if (!controller.signal.aborted) { setError(asBusinessError(cause).message); setOptions([]); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); }, 200);
    return () => { window.clearTimeout(timer); controller.abort(); };
  }, [workspaceId, kind, query, attempt, excludeId]);
  return <div className={styles.stack}><label className={styles.field}>Search permitted {kind}<input type="search" value={query} onChange={event => { setQuery(event.target.value); onSelect(null); }} disabled={disabled} placeholder={`Search ${kind}`} maxLength={160} /></label>{error ? <div role="alert" className={styles.error}><p>{error}</p><button className={styles.button} type="button" onClick={() => setAttempt(value => value + 1)}>Retry search</button></div> : null}<label className={styles.field}>Choose {kind === "files" ? "a Library file" : `a ${kind.slice(0, -1)}`}<select value={selected} disabled={disabled || loading || Boolean(error)} onChange={event => onSelect(options.find(option => option.id === event.target.value) || null)}><option value="">{loading ? "Loading…" : options.length ? "Choose an existing record" : "No permitted records found"}</option>{options.map(option => <option key={option.id} value={option.id}>{option.title}</option>)}</select></label><p className={styles.small}>Only records available to you in this workspace can be linked.</p></div>;
}
export function WorkSection({ detail, workspaceId, members, mutation, disabled, onOpenTask, onOpenProject, onDirty }: { detail: BusinessDetail; workspaceId: string; members: Members; mutation: MutationController; disabled: boolean; onOpenTask?: (id: string) => void; onOpenProject?: (id: string) => void; onDirty: (value: boolean) => void }) {
  const [linking, setLinking] = useState<"tasks" | "projects" | null>(null);
  const [option, setOption] = useState<BusinessOption | null>(null);
  const [remove, setRemove] = useState<{ kind: "tasks" | "projects"; id: string; title: string } | null>(null);
  const editable = detail.plan.state !== "archived";
  const context = { plan_id: detail.plan.id, expected_revision: detail.plan.revision };
  return <div><div className={styles.header}><div><h2>Work & projects</h2><p className={styles.muted}>Live canonical records. Task changes here and in Tasks refer to the same IDs.</p></div>{editable ? <div className={styles.row}><button className={styles.button} disabled={disabled || Boolean(linking)} onClick={() => { setLinking("tasks"); setOption(null); onDirty(true); }}>Link existing task</button><button className={styles.button} disabled={disabled || Boolean(linking)} onClick={() => { setLinking("projects"); setOption(null); onDirty(true); }}>Link related project</button></div> : null}</div>
    {linking ? <form className={styles.panel} onSubmit={event => { event.preventDefault(); if (disabled || !option) return; mutation.mutate(linking === "tasks" ? "linkTask" : "linkProject", { ...context, [linking === "tasks" ? "task_id" : "project_id"]: option.id }, "Existing record linked to this plan.", () => { setLinking(null); setOption(null); onDirty(false); }); }}><h3>Link {linking === "tasks" ? "an existing task" : "a related project"}</h3><LinkSelector excludeId={linking === "projects" ? detail.plan.id : undefined} key={linking} workspaceId={workspaceId} kind={linking} selected={option?.id || ""} onSelect={setOption} disabled={disabled} /><div className={styles.row}><button className={styles.primary} disabled={disabled || !option}>Link selected record</button><button className={styles.button} type="button" disabled={disabled} onClick={() => { setLinking(null); setOption(null); onDirty(false); }}>Cancel</button></div></form> : null}
    {remove ? <div className={styles.notice}><p>Unlink “{remove.title}” from this draft? The original {remove.kind === "tasks" ? "task" : "project"} is kept.</p><div className={styles.row}><button className={styles.danger} disabled={disabled} onClick={() => mutation.mutate(remove.kind === "tasks" ? "unlinkTask" : "unlinkProject", { ...context, [remove.kind === "tasks" ? "task_id" : "project_id"]: remove.id }, "Record unlinked. Its original is unchanged.", () => setRemove(null))}>Unlink</button><button className={styles.button} disabled={disabled} onClick={() => setRemove(null)}>Cancel</button></div></div> : null}
    <section className={styles.panel}><h3>Linked tasks ({detail.tasks.length})</h3>{detail.tasks.length ? <ul className={styles.list}>{detail.tasks.map(task => { const swotLinked = detail.swot.some(entry => entry.task_id === task.id); return <li key={task.id}><div className={styles.spread}><h3>{task.title}</h3><Badge tone={task.status === "done" ? "approved" : undefined}>{label(task.status)}</Badge></div>{task.details ? <p className={styles.prose}>{task.details}</p> : null}<div className={styles.metadata}><span>{memberName(members, task.assigned_to)}</span><span>Due {dateLabel(task.due_date)}</span><span>{label(task.priority)} priority</span>{swotLinked ? <span>SWOT response</span> : null}</div>{task.blocked_reason ? <p className={styles.notice}>Blocked: {task.blocked_reason}</p> : null}<div className={styles.row} style={{ marginTop: 12 }}>{onOpenTask ? <button className={styles.button} disabled={disabled || Boolean(linking)} onClick={() => onOpenTask(task.id)}>Open in Tasks</button> : <p className={styles.small}>Edit assignee, due date, status and checklist in Tasks.</p>}{editable && !swotLinked ? <button className={styles.button} disabled={disabled || Boolean(linking)} onClick={() => setRemove({ kind: "tasks", id: task.id, title: task.title })}>Unlink task</button> : null}</div><p className={styles.small} style={{ overflowWrap: "anywhere", marginTop: 10 }}>Task ID: {task.id}</p></li>; })}</ul> : <Empty title="No linked work">Link an existing task or create a response task from SWOT.</Empty>}</section>
    <section className={styles.panel}><h3>Linked related projects ({detail.projects.length})</h3>{detail.projects.length ? <ul className={styles.list}>{detail.projects.map(project => <li key={project.id}><div className={styles.spread}><strong>{project.title}</strong><div className={styles.row}>{onOpenProject ? <button className={styles.button} disabled={disabled || Boolean(linking)} onClick={() => onOpenProject(project.id)}>Open project</button> : null}{editable ? <button className={styles.button} disabled={disabled || Boolean(linking)} onClick={() => setRemove({ kind: "projects", id: project.id, title: project.title })}>Unlink</button> : null}</div></div><p className={styles.small} style={{ overflowWrap: "anywhere" }}>Project ID: {project.id}</p></li>)}</ul> : <p className={styles.muted}>No related projects linked.</p>}</section>
  </div>;
}
export function DocumentsSection({ workspaceId, detail, mutation, disabled, onDirty, onOpenFile }: { workspaceId: string; detail: BusinessDetail; mutation: MutationController; disabled: boolean; onDirty: (value: boolean) => void; onOpenFile?: (id: string) => void }) {
  const [adding, setAdding] = useState(false);
  const [kind, setKind] = useState<"file" | "url">("file");
  const [file, setFile] = useState<BusinessOption | null>(null);
  const [title, setTitle] = useState("");
  const [url, setUrl] = useState("");
  const [notes, setNotes] = useState("");
  const [remove, setRemove] = useState<string | null>(null);
  const editable = detail.plan.state !== "archived";
  const valid = kind === "file" ? Boolean(file) : Boolean(safeBusinessUrl(url) && title.trim());
  function reset() { setAdding(false); setFile(null); setTitle(""); setUrl(""); setNotes(""); onDirty(false); }
  return <div><div className={styles.header}><div><h2>Supporting documents</h2><p className={styles.muted}>Link existing permitted Library files or ordinary HTTPS references.</p></div>{editable ? <button className={styles.primary} disabled={disabled || adding} onClick={() => { setAdding(true); onDirty(true); }}>Link document</button> : null}</div><p className={styles.notice}>These links are workspace-visible. Do not add confidential contracts or financial records here. Opening an external link still depends on that provider’s access permissions. This feature does not upload documents or grant file access.</p>
    {adding ? <form className={styles.panel} onSubmit={event => { event.preventDefault(); if (disabled || !valid) return; mutation.mutate("linkDocument", { plan_id: detail.plan.id, expected_revision: detail.plan.revision, ...(kind === "file" ? { file_id: file!.id } : { url: safeBusinessUrl(url), title: title.trim() }), notes }, "Supporting document linked.", reset); }}><div className={styles.form}><fieldset disabled={disabled}><label className={styles.field}>Document source<select value={kind} onChange={event => setKind(event.target.value as typeof kind)}><option value="file">Existing Library file</option><option value="url">External HTTPS document link</option></select></label>{kind === "file" ? <LinkSelector workspaceId={workspaceId} kind="files" selected={file?.id || ""} disabled={disabled} onSelect={option => { setFile(option); if (option && !title) setTitle(option.title); }} /> : <label className={styles.field}>HTTPS document URL<input type="url" required value={url} onChange={event => setUrl(event.target.value)} maxLength={3000} placeholder="https://…" />{url && !safeBusinessUrl(url) ? <small>Use a valid HTTPS URL without embedded sign-in credentials.</small> : null}</label>}{kind === "url" ? <label className={styles.field}>Title<input value={title} onChange={event => setTitle(event.target.value)} required maxLength={240} /></label> : file ? <p className={styles.muted}>Linked with its original Library title: {file.title}</p> : null}<label className={styles.field}>Notes<textarea value={notes} onChange={event => setNotes(event.target.value)} maxLength={2000} /></label><div className={styles.row}><button className={styles.primary} disabled={!valid}>Link document</button><button className={styles.button} type="button" onClick={reset}>Cancel</button></div></fieldset></div></form> : null}
    {detail.documents.length ? <ul className={`${styles.list} ${styles.panel}`}>{detail.documents.map(document => { const safeUrl = safeBusinessUrl(document.url); return <li key={document.id}><div className={styles.spread}><div><h3>{document.title || "Untitled document"}</h3><p className={styles.small}>{document.file_id ? "Existing Library file" : "External reference"} · Linked {dateLabel(document.created_at)}</p></div>{editable ? <button className={styles.button} disabled={disabled || adding} onClick={() => setRemove(document.id)}>Unlink</button> : null}</div>{document.notes ? <p className={styles.prose}>{document.notes}</p> : null}{safeUrl ? <a href={safeUrl} target="_blank" rel="noopener noreferrer" className={styles.link}>Open external document (new tab)</a> : document.file_id ? <div className={styles.stack}>{onOpenFile ? <button className={styles.button} disabled={disabled || adding} onClick={() => onOpenFile(document.file_id!)}>Open original in Library</button> : <span className={styles.small}>Find this original in Library.</span>}<span className={styles.small} style={{ overflowWrap: "anywhere" }}>File ID: {document.file_id}</span></div> : <p className={styles.muted}>This reference has no valid HTTPS destination.</p>}{remove === document.id ? <div className={styles.notice}><p>Unlink this document from the draft? The source file and immutable snapshots remain unchanged.</p><div className={styles.row}><button className={styles.danger} disabled={disabled} onClick={() => mutation.mutate("unlinkDocument", { plan_id: detail.plan.id, expected_revision: detail.plan.revision, id: document.id }, "Document unlinked from the draft.", () => setRemove(null))}>Unlink document</button><button className={styles.button} disabled={disabled} onClick={() => setRemove(null)}>Cancel</button></div></div> : null}</li>; })}</ul> : <Empty title="No supporting documents linked">Choose an existing Library record or add an HTTPS reference.</Empty>}
  </div>;
}
