"use client";

import { useState } from "react";
import type { BusinessDetail, BusinessSwot } from "../../../lib/studio/business/contracts";
import { Badge, Empty, OwnerSelect, label, memberName, type Members, type MutationController } from "./ui";
import styles from "./business.module.css";

const quadrants: BusinessSwot["quadrant"][] = ["strength", "weakness", "opportunity", "threat"];
export function SwotSection({ detail, members, mutation, disabled, onOpenTask, onDirty }: { detail: BusinessDetail; members: Members; mutation: MutationController; disabled: boolean; onOpenTask?: (id: string) => void; onDirty: (value: boolean) => void }) {
  const [editing, setEditing] = useState<BusinessSwot | "new" | null>(null);
  const [taskEntry, setTaskEntry] = useState<BusinessSwot | null>(null);
  const [removing, setRemoving] = useState<string | null>(null);
  const editable = detail.plan.state !== "archived";
  return <div><div className={styles.header}><div><h2>SWOT</h2><p className={styles.muted}>Connect observations to accountable work in the shared Tasks board.</p></div>{editable ? <button className={styles.primary} disabled={disabled || Boolean(editing || taskEntry)} onClick={() => { setEditing("new"); onDirty(true); }}>Add SWOT entry</button> : null}</div>
    {editing ? <div className={styles.panel}><h3>{editing === "new" ? "New SWOT entry" : "Edit SWOT entry"}</h3><SwotEditor key={editing === "new" ? "new" : editing.id} entry={editing === "new" ? undefined : editing} revision={detail.plan.revision} members={members} disabled={disabled} onCancel={() => { setEditing(null); onDirty(false); }} onSave={input => mutation.mutate("upsertSwot", { ...input, plan_id: detail.plan.id }, "SWOT entry saved.", () => { setEditing(null); onDirty(false); })} /></div> : null}
    {taskEntry ? <div className={styles.panel}><h3>Create response task</h3><p className={styles.muted}>This creates one canonical task assigned to {memberName(members, taskEntry.owner_id)}. It will also appear in Tasks.</p><SwotTaskForm key={taskEntry.id} entry={taskEntry} disabled={disabled} onCancel={() => { setTaskEntry(null); onDirty(false); }} onSave={input => mutation.mutate("createSwotTask", { ...input, id: taskEntry.id, plan_id: detail.plan.id, expected_revision: detail.plan.revision }, "The response task is linked here and available in Tasks.", () => { setTaskEntry(null); onDirty(false); })} /></div> : null}
    {detail.swot.length === 0 && !editing ? <Empty title="No SWOT entries yet">Capture a strength, weakness, opportunity or threat, then give it an owner and response task.</Empty> : <div className={styles.grid}>{quadrants.map(quadrant => <section className={styles.panel} key={quadrant}><h3>{label(quadrant)}</h3>{detail.swot.filter(entry => entry.quadrant === quadrant).length === 0 ? <p className={styles.muted}>No entries.</p> : <ul className={styles.list}>{detail.swot.filter(entry => entry.quadrant === quadrant).map(entry => { const task = detail.tasks.find(row => row.id === entry.task_id); return <li key={entry.id}><p className={styles.prose}>{entry.body}</p>{entry.evidence ? <p className={styles.quote}>{entry.evidence}</p> : null}<p className={styles.small}>SWOT owner: {memberName(members, entry.owner_id)}</p>{entry.task_id ? <div className={styles.stack}><div className={styles.row}><Badge>{task ? label(task.status) : "Linked task"}</Badge>{task ? <span className={styles.small}>Task owner: {memberName(members, task.assigned_to)}</span> : null}</div>{onOpenTask ? <button className={styles.button} disabled={disabled || Boolean(editing || taskEntry)} onClick={() => onOpenTask(entry.task_id!)}>Open task: {task?.title || "Response task"}</button> : <p className={styles.small}>Edit this linked task in the Tasks board.</p>}<span className={styles.small} style={{ overflowWrap: "anywhere" }}>Task ID: {entry.task_id}</span></div> : editable ? <button className={styles.button} disabled={disabled || Boolean(editing || taskEntry)} onClick={() => { setTaskEntry(entry); onDirty(true); }}>Create response task</button> : null}{editable ? <div className={styles.row} style={{ marginTop: 12 }}><button className={styles.button} disabled={disabled || Boolean(editing || taskEntry)} onClick={() => { setEditing(entry); onDirty(true); }}>Edit</button><button className={styles.danger} disabled={disabled || Boolean(editing || taskEntry)} onClick={() => setRemoving(entry.id)}>Remove</button></div> : null}{removing === entry.id ? <div className={styles.notice}><p>Remove this SWOT entry from the working draft? Any canonical task will remain in Tasks.</p><div className={styles.row}><button className={styles.danger} disabled={disabled} onClick={() => mutation.mutate("removeSwot", { plan_id: detail.plan.id, expected_revision: detail.plan.revision, id: entry.id }, "SWOT entry removed from the draft.", () => setRemoving(null))}>Remove entry</button><button className={styles.button} disabled={disabled} onClick={() => setRemoving(null)}>Cancel</button></div></div> : null}</li>; })}</ul>}</section>)}</div>}
  </div>;
}
function SwotEditor({ entry, revision, members, disabled, onSave, onCancel }: { entry?: BusinessSwot; revision: number; members: Members; disabled: boolean; onSave: (input: Record<string, unknown>) => void; onCancel: () => void }) {
  const [quadrant, setQuadrant] = useState(entry?.quadrant || "strength");
  const [body, setBody] = useState(entry?.body || "");
  const [evidence, setEvidence] = useState(entry?.evidence || "");
  const [owner, setOwner] = useState(entry?.owner_id || "");
  const [baseRevision, setBaseRevision] = useState(revision);
  return <form className={styles.form} onSubmit={event => { event.preventDefault(); if (!disabled && revision === baseRevision) onSave({ ...(entry ? { id: entry.id } : {}), quadrant, body: body.trim(), evidence, owner_id: owner || null, expected_revision: baseRevision }); }}>{revision !== baseRevision ? <div className={styles.notice}><p>The plan changed while this form was open. Your entry text was kept. Review the current SWOT below before replacing or adding this entry.</p><button className={styles.button} type="button" onClick={() => setBaseRevision(revision)}>Use my entry with the refreshed revision</button></div> : null}<fieldset disabled={disabled}><div className={styles.split}><label className={styles.field}>Quadrant<select value={quadrant} onChange={event => setQuadrant(event.target.value as typeof quadrant)}>{quadrants.map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label><OwnerSelect members={members} value={owner} onChange={setOwner} /></div><label className={styles.field}>Observation<textarea value={body} onChange={event => setBody(event.target.value)} required maxLength={4000} autoFocus /></label><label className={styles.field}>Evidence or source<textarea value={evidence} onChange={event => setEvidence(event.target.value)} maxLength={2000} /></label>{entry?.task_id ? <p className={styles.muted}>A response task is already linked. Manage its current assignee and status in Tasks.</p> : null}<div className={styles.row}><button className={styles.primary} disabled={revision !== baseRevision || !body.trim()}>Save entry</button><button type="button" className={styles.button} onClick={onCancel}>Cancel</button></div></fieldset></form>;
}
function SwotTaskForm({ entry, disabled, onSave, onCancel }: { entry: BusinessSwot; disabled: boolean; onSave: (input: Record<string, unknown>) => void; onCancel: () => void }) {
  const [title, setTitle] = useState(entry.body.slice(0, 240));
  const [due, setDue] = useState("");
  const [priority, setPriority] = useState("normal");
  return <form className={styles.form} onSubmit={event => { event.preventDefault(); if (!disabled) onSave({ title: title.trim(), due_date: due || null, priority }); }}><fieldset disabled={disabled}><label className={styles.field}>Task title<input required maxLength={240} value={title} onChange={event => setTitle(event.target.value)} autoFocus /></label><div className={styles.split}><label className={styles.field}>Due date<input type="date" value={due} onChange={event => setDue(event.target.value)} /></label><label className={styles.field}>Priority<select value={priority} onChange={event => setPriority(event.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div><div className={styles.row}><button className={styles.primary} disabled={!title.trim()}>Create and link task</button><button className={styles.button} type="button" onClick={onCancel}>Cancel</button></div></fieldset></form>;
}
