"use client";

import { useEffect, useState } from "react";
import type { BusinessDetail, BusinessSnapshot } from "../../../lib/studio/business/contracts";
import { safeBusinessUrl } from "../../../lib/studio/business/client";
import { Badge, Empty, dateLabel, label, memberName, memberLabel, type Members, type MutationController } from "./ui";
import styles from "./business.module.css";

export function VersionHistory({ detail, members, userId, mutation, disabled, initialFinal = false, onOpenFile, onDirty }: { detail: BusinessDetail; members: Members; userId: string; mutation: MutationController; disabled: boolean; initialFinal?: boolean; onOpenFile?: (id: string) => void; onDirty?: (dirty: boolean) => void }) {
  const versions = [...detail.versions].sort((a, b) => b.ordinal - a.ordinal);
  const [selected, setSelected] = useState<string | null>(() => initialFinal ? detail.plan.approved_version_id : versions[0]?.id || null);
  const version = versions.find(item => item.id === selected) || versions[0];
  const [decisionDirty, setDecisionDirty] = useState(false);
  function markDirty(value: boolean) { setDecisionDirty(value); onDirty?.(value); }
  const currentFinal = versions.find(item => item.id === detail.plan.approved_version_id);
  const currentReview = detail.reviews.find(review => review.version_id === version?.id);
  return <div>
    {currentFinal ? <div className={styles.notice}><strong>Current final: version {currentFinal.ordinal}</strong><p>The saved draft may contain newer changes. Approved snapshots are immutable.</p><button className={styles.button} disabled={decisionDirty || mutation.blocked} onClick={() => setSelected(currentFinal.id)}>View current final</button></div> : <p className={styles.muted}>No final has been approved. Submitting a version starts a review; it does not approve it.</p>}
    {version ? <><label className={styles.field}>Version to inspect<select disabled={decisionDirty || mutation.blocked} value={version.id} onChange={event => setSelected(event.target.value)}>{versions.map(item => { const review = detail.reviews.find(row => row.version_id === item.id); return <option key={item.id} value={item.id}>Version {item.ordinal} · {item.id === detail.plan.approved_version_id ? "Current final" : review?.status === "approved" ? "Superseded final" : label(review?.status || "Snapshot")}</option>; })}</select></label><SnapshotView version={version} detail={detail} members={members} onOpenFile={onOpenFile} disabled={disabled} />{currentReview?.status === "open" && version.reviewers.includes(userId) ? <ReviewDecision key={version.id} version={version} reviewRevision={currentReview.revision} decided={detail.decisions.some(decision => decision.version_id === version.id && decision.reviewer_id === userId)} disabled={disabled} mutation={mutation} onDirty={markDirty} /> : currentReview?.status === "open" ? <p className={styles.notice}>This version is waiting for its named reviewers. You are not assigned to approve it.</p> : null}</> : <Empty title="No submitted versions">Save a plan and choose reviewers to create the first immutable review snapshot.</Empty>}
  </div>;
}
function SnapshotView({ version, detail, members, onOpenFile, disabled }: { version: BusinessSnapshot; detail: BusinessDetail; members: Members; onOpenFile?: (id: string) => void; disabled: boolean }) {
  const review = detail.reviews.find(item => item.version_id === version.id);
  const decisions = detail.decisions.filter(item => item.version_id === version.id);
  const supersededVersion = detail.versions.find(item => item.id === version.supersedes_version_id);
  const approved = review?.status === "approved";
  return <article className={styles.panel} style={{ marginTop: 18 }} aria-label={`Immutable version ${version.ordinal}`}>
    <div className={styles.spread}><div><p className={styles.eyebrow}>Immutable snapshot · Version {version.ordinal}</p><h2>{version.body.title}</h2></div><Badge tone={approved ? "approved" : review?.status === "open" ? "in_review" : undefined}>{approved ? (version.id === detail.plan.approved_version_id ? "Current final" : "Superseded final") : label(review?.status || "Snapshot")}</Badge></div>
    <div className={styles.metadata}><span>Submitted {dateLabel(version.created_at, true)}</span><span>Draft revision {version.plan_revision}</span><span>Owner: {memberName(members, version.body.owner_id)}</span><span>Target: {dateLabel(version.body.target_date)}</span></div>
    {approved ? <p className={styles.success}>Approved {dateLabel(review?.decided_at, true)} under the all-reviewers policy.</p> : null}
    {supersededVersion ? <p className={styles.muted}>{approved ? "Replaces" : "Proposed replacement for"} final version {supersededVersion.ordinal}. Its original snapshot and decisions remain in this history.</p> : null}
    <section style={{ marginTop: 20 }}><h3>Brief</h3><p className={styles.prose}>{version.body.brief || "No brief in this snapshot."}</p><h3>Objective</h3><p className={styles.prose}>{version.body.objective || "No objective in this snapshot."}</p><h3>Notes</h3><p className={styles.prose}>{version.body.notes || "No notes in this snapshot."}</p><p className={styles.muted}>Category: {version.body.category || "None"} · Tags: {version.body.tags.join(", ") || "None"}</p></section>
    <h3>Snapshot SWOT</h3>{version.body.swot.length ? <ul className={styles.list}>{version.body.swot.map(entry => <li key={entry.id}><Badge>{label(entry.quadrant)}</Badge><p className={styles.prose}>{entry.body}</p>{entry.evidence ? <p className={styles.quote}>{entry.evidence}</p> : null}<p className={styles.small}>Owner: {memberName(members, entry.owner_id)}{entry.task_id ? ` · Linked task ID: ${entry.task_id}` : ""}</p></li>)}</ul> : <p className={styles.muted}>No SWOT entries captured.</p>}
    <details><summary>Captured link references</summary><p className={styles.muted}>These are the exact IDs captured with the version. Linked tasks and projects remain live records; their later edits do not rewrite this snapshot.</p><h3>Tasks</h3><p className={styles.prose}>{version.body.task_ids.join("\n") || "None"}</p><h3>Projects</h3><p className={styles.prose}>{version.body.project_ids.join("\n") || "None"}</p><h3>Documents</h3>{version.body.document_references?.length ? <ul className={styles.list}>{version.body.document_references.map(reference => { const url = safeBusinessUrl(reference.url); return <li key={reference.id}>{reference.file_id ? <><p className={styles.small} style={{ overflowWrap: "anywhere" }}>Library file ID: {reference.file_id}</p>{onOpenFile ? <button className={styles.button} disabled={disabled} onClick={() => onOpenFile(reference.file_id!)}>Open original in Library</button> : null}</> : url ? <a className={styles.link} href={url} target="_blank" rel="noopener noreferrer">{reference.title || "External document"} (new tab)</a> : <span>Reference {reference.id}</span>}</li>; })}</ul> : <p className={styles.prose}>{version.body.document_ids.join("\n") || "None"}</p>}<p className={styles.small}>File access is checked when you open the original. External references retain their captured URL; this does not grant access or freeze the remote document contents.</p></details>
    <section style={{ marginTop: 22 }}><h3>Explicit decisions on version {version.ordinal}</h3><p className={styles.muted}>Every named reviewer must approve this exact version. Business approval does not authorize spending, signing, wider sharing, or publication.</p><ul className={styles.list}>{version.reviewers.map(id => { const decision = decisions.find(row => row.reviewer_id === id); return <li key={id}><div className={styles.spread}><strong>{memberName(members, id)}</strong><Badge tone={decision?.disposition === "approve" ? "approved" : undefined}>{decision ? label(decision.disposition) : "No decision recorded"}</Badge></div>{decision ? <><p className={styles.small}>{dateLabel(decision.created_at, true)}</p><p className={styles.quote}>{decision.rationale || "No rationale provided."}</p></> : null}</li>; })}</ul></section>
  </article>;
}
function ReviewDecision({ version, reviewRevision, decided, disabled, mutation, onDirty }: { version: BusinessSnapshot; reviewRevision: number; decided: boolean; disabled: boolean; mutation: MutationController; onDirty: (dirty: boolean) => void }) {
  const [disposition, setDisposition] = useState<"approve" | "request_changes">("approve");
  const [rationale, setRationale] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  useEffect(() => { setConfirmed(false); }, [reviewRevision]);
  if (decided) return <p className={styles.notice}>Your decision on this version is recorded. Remaining reviewers must make their own decisions.</p>;
  return <form className={styles.panel} onSubmit={event => { event.preventDefault(); if (disabled || !confirmed) return; mutation.mutate("decidePlan", { plan_id: version.plan_id, version_id: version.id, expected_review_revision: reviewRevision, disposition, rationale }, `Your decision on version ${version.ordinal} was recorded.`, () => { setConfirmed(false); setRationale(""); onDirty(false); }); }}><h3>Your decision on version {version.ordinal}</h3><fieldset className={styles.fieldset} disabled={disabled}><div className={styles.form}><label className={styles.field}>Decision<select value={disposition} onChange={event => { setDisposition(event.target.value as typeof disposition); setConfirmed(false); onDirty(true); }}><option value="approve">Approve this exact version</option><option value="request_changes">Request changes</option></select></label><label className={styles.field}>Rationale<textarea value={rationale} onChange={event => { setRationale(event.target.value); onDirty(true); }} maxLength={4000} required={disposition === "request_changes"} placeholder={disposition === "request_changes" ? "Explain what needs to change." : "Why are you approving this version? (optional)"} /></label><label className={styles.checkbox}><input type="checkbox" checked={confirmed} onChange={event => { setConfirmed(event.target.checked); onDirty(true); }} required /><span>I reviewed version {version.ordinal} above and explicitly choose to {disposition === "approve" ? "approve it" : "request changes"}.</span></label><button className={styles.primary} disabled={!confirmed || (disposition === "request_changes" && !rationale.trim())}>{disposition === "approve" ? `Approve version ${version.ordinal}` : `Request changes to version ${version.ordinal}`}</button><button type="button" className={styles.button} onClick={() => { setRationale(""); setConfirmed(false); setDisposition("approve"); onDirty(false); }}>Discard decision inputs</button></div></fieldset></form>;
}
export function SubmitReview({ detail, members, mutation, disabled, onDirty }: { detail: BusinessDetail; members: Members; mutation: MutationController; disabled: boolean; onDirty?: (dirty: boolean) => void }) {
  const [reviewers, setReviewers] = useState<string[]>([]);
  const [confirm, setConfirm] = useState(false);
  const priorFinal = detail.versions.find(version => version.id === detail.plan.approved_version_id);
  useEffect(() => { setConfirm(false); }, [detail.plan.revision, detail.plan.approved_version_id]);
  const selected = reviewers.filter(id => members.some(member => member.user_id === id));
  if (detail.plan.kind !== "plan") return <p className={styles.notice}>Develop this {detail.plan.kind} into a plan before submitting it for review.</p>;
  if (detail.plan.state === "archived") return null;
  if (detail.reviews.some(review => review.status === "open")) return <p className={styles.notice}>A version is already under review. Inspect that version and its decisions in Versions & review.</p>;
  return <form className={styles.panel} onSubmit={event => { event.preventDefault(); if (disabled || !confirm || !selected.length) return; mutation.mutate("submitPlan", { plan_id: detail.plan.id, expected_revision: detail.plan.revision, reviewers: selected, policy: "all_reviewers", supersedes_version_id: detail.plan.approved_version_id || null }, "An immutable version was submitted for review.", () => { setReviewers([]); setConfirm(false); onDirty?.(false); }); }}><h3>Submit a saved version for review</h3><p className={styles.muted}>The server captures the current saved draft, SWOT and link IDs. All selected reviewers must explicitly approve the same version.</p><fieldset className={styles.fieldset} disabled={disabled}><legend>Required reviewers</legend>{members.map(member => <label className={styles.checkbox} key={member.user_id}><input type="checkbox" checked={selected.includes(member.user_id)} onChange={event => { setConfirm(false); onDirty?.(true); setReviewers(previous => event.target.checked ? [...previous, member.user_id] : previous.filter(id => id !== member.user_id)); }} /><span>{memberLabel(member)}</span></label>)}{members.length === 0 ? <p className={styles.muted}>No eligible workspace members are available.</p> : null}<label className={styles.checkbox}><input type="checkbox" checked={confirm} onChange={event => { setConfirm(event.target.checked); onDirty?.(true); }} required /><span>{priorFinal ? `I intend this version to supersede final version ${priorFinal.ordinal} only after every selected reviewer approves. The existing final remains effective until then.` : "I confirm these reviewers and the all-reviewers approval policy for this exact saved draft."}</span></label><button className={styles.primary} disabled={!selected.length || !confirm}>Submit saved draft for review</button>{selected.length || confirm ? <button type="button" className={styles.button} onClick={() => { setReviewers([]); setConfirm(false); onDirty?.(false); }} style={{ marginLeft: 8 }}>Clear review selection</button> : null}</fieldset></form>;
}
