import {authorize} from '../server';
import {StudioError,uuidPattern} from '../contracts';
import {PRIVATE_BUSINESS_SCHEMA,type PrivateMutation} from './contracts';
function safeDatabaseError(error:{code?:string}):StudioError {if(['42P01','PGRST202','PGRST205','42703'].includes(error.code??''))return new StudioError('Private records setup is required. Apply the reviewed schema before saving.','SCHEMA_REQUIRED',503);if(error.code==='42501')return new StudioError('This private register is unavailable or your permission changed.','FORBIDDEN',403);if(error.code==='40001')return new StudioError('This record changed. Reload before making a new edit.','CONFLICT',409);if(['22023','23514','22P02','23502','23503','23505','22007','22008','22003'].includes(error.code??''))return new StudioError('Check the record fields, dates, current member and same-register links. No changes were saved.','VALIDATION',422);return new StudioError('Private records are temporarily unavailable. Retry the same request.','DATABASE_ERROR',503)}
async function capability(workspaceId:string,expectedUserId:unknown){
 // This is an intent check, never an authentication claim. A stale tab or retry
 // must not become an operation by whichever account owns the current cookie.
 if(typeof expectedUserId!=='string'||!uuidPattern.test(expectedUserId))throw new StudioError('A valid intended account is required.','VALIDATION',422);
 const auth=await authorize(workspaceId);
 if(auth.user.id.toLowerCase()!==expectedUserId.toLowerCase())throw new StudioError('Your signed-in account changed. Private records were cleared. Reopen the view with your current account.','ACCOUNT_CHANGED',403);
 const {data,error}=await auth.client.rpc('studio_private_business_capabilities',{p_workspace:workspaceId});if(error)throw safeDatabaseError(error);if(data?.schemaVersion!==PRIVATE_BUSINESS_SCHEMA||data?.restrictedRecords!==true)throw new StudioError('Private records setup is required.','SCHEMA_REQUIRED',503);return auth;
}
export async function readPrivateBusiness(params:URLSearchParams){const workspaceId=params.get('workspaceId')??'';const {client}=await capability(workspaceId,params.get('expectedUserId'));const page=Number(params.get('page')??0);if(!Number.isSafeInteger(page)||page<0||page>100000)throw new StudioError('Invalid page.','VALIDATION');if(params.get('recordId')&&!params.get('bookId'))throw new StudioError('A register is required for a record.','VALIDATION');for(const name of ['bookId','recordId'])if(params.get(name)&&!uuidPattern.test(params.get(name)!))throw new StudioError('Invalid identifier.','VALIDATION');const {data,error}=await client.rpc('studio_private_business_read',{p_workspace:workspaceId,p_book:params.get('bookId')||null,p_record:params.get('recordId')||null,p_kind:params.get('kind')||'all',p_page:page,p_query:params.get('q')||'',p_options:params.get('options')||null});if(error)throw safeDatabaseError(error);return data;}
export async function mutatePrivateBusiness(mutation:PrivateMutation){const {client}=await capability(mutation.workspaceId,mutation.expectedUserId);const {data,error}=await client.rpc('studio_private_business_mutate',{p_workspace:mutation.workspaceId,p_operation:mutation.operation,p_request:mutation.requestId,p_input:mutation.input});if(error)throw safeDatabaseError(error);return data;}
