import { requestOrigin } from './request-origin-test-loader.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const root=new URL('../',import.meta.url);
function load(path,deps={}){const code=ts.transpileModule(fs.readFileSync(new URL(path,root),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const context={exports:{},Response,Request,URL,URLSearchParams,TextEncoder,crypto,require:key=>{if(!(key in deps))throw Error('Unexpected dependency: '+key);return deps[key]}};vm.runInNewContext(code,context);return context.exports}
const shared=load('lib/studio/contracts.ts');
const contracts=load('lib/studio/business/contracts.ts',{'../contracts':shared});
const w='10000000-0000-4000-8000-000000000001',r='20000000-0000-4000-8000-000000000001';
const valid={workspaceId:w,requestId:r,operation:'createPlan',input:{title:'Business'}};
const validate=contracts.validateBusinessMutation;
const invalid=x=>assert.throws(()=>validate(x),err=>err.code==='VALIDATION');
test('contract accepts bounded identified plan creation',()=>assert.equal(validate(valid).operation,'createPlan'));
test('contract rejects absent and forged input identities',()=>{invalid(null);invalid({...valid,workspaceId:'x'});invalid({...valid,input:{title:'X',created_by:w}});invalid({...valid,input:{title:'X',state:'approved'}})});
test('contract enforces update and version review revisions separately',()=>{invalid({...valid,operation:'updatePlan',input:{plan_id:w}});invalid({...valid,operation:'decidePlan',input:{plan_id:w,version_id:r,expected_revision:0}});assert.equal(validate({...valid,operation:'decidePlan',input:{plan_id:w,version_id:r,expected_review_revision:0}}).operation,'decidePlan')});
test('contract rejects bad foreign IDs and oversized inputs',()=>{invalid({...valid,input:{owner_id:'bad'}});assert.throws(()=>validate({...valid,input:{notes:'x'.repeat(60001)}}),e=>e.status===413)});
function route(overrides={}){let reads=0,writes=0;const api=load('app/api/studio/business/route.ts',{'@/lib/studio/request-origin':requestOrigin,'@/lib/studio/contracts':shared,'@/lib/studio/business/contracts':contracts,'@/lib/studio/business/server':{readBusiness:async()=>{reads++;return {plans:[]}},mutateBusiness:async()=>{writes++;return {plan:{id:w}}},...overrides}});return {...api,counts:()=>({reads,writes})}}
const post=(payload=valid,headers={})=>new Request('https://fairway.example/api/studio/business',{method:'POST',headers:{'content-type':'application/json',...headers},body:typeof payload==='string'?payload:JSON.stringify(payload)});
test('HTTP GET is explicitly private and noncached',async()=>{const api=route();const res=await api.GET(new Request('https://fairway.example/api/studio/business?workspaceId='+w));assert.equal(res.status,200);assert.equal(res.headers.get('Cache-Control'),'private, no-store');assert.equal(res.headers.get('Vary'),'Cookie');assert.equal(api.counts().reads,1)});
test('HTTP POST rejects cross-origin and cross-site writes before mutation',async()=>{const api=route();assert.equal((await api.POST(post(valid,{origin:'https://evil.example'}))).status,403);assert.equal((await api.POST(post(valid,{'sec-fetch-site':'cross-site'}))).status,403);assert.equal(api.counts().writes,0)});
test('HTTP POST rejects invalid JSON and oversized unicode bytes',async()=>{const api=route();assert.equal((await api.POST(post('{bad'))).status,400);assert.equal((await api.POST(post({...valid,input:{notes:'💧'.repeat(20000)}}))).status,413);assert.equal(api.counts().writes,0)});
test('HTTP POST only returns server-confirmed success',async()=>{const api=route();const res=await api.POST(post());assert.equal(res.status,200);assert.equal((await res.json()).data.plan.id,w);assert.equal(api.counts().writes,1)});
test('HTTP conflict, denied and schema errors retain exact status with no cache',async()=>{for(const [code,status]of[['CONFLICT',409],['FORBIDDEN',403],['SCHEMA_REQUIRED',503]]){const api=route({mutateBusiness:async()=>{throw new shared.StudioError('Fixture',code,status)}});const res=await api.POST(post());assert.equal(res.status,status);assert.equal((await res.json()).code,code);assert.equal(res.headers.get('Cache-Control'),'private, no-store')}});
test('HTTP internal errors do not expose SQL, credentials or stack',async()=>{const api=route({readBusiness:async()=>{throw Error('SQL secret')}});const res=await api.GET(new Request('https://fairway.example'));assert.equal(res.status,500);assert.equal(JSON.stringify(await res.json()).includes('secret'),false)});
function server(config={}){const calls=[];const client={rpc:async(name,input)=>{calls.push({name,input});if(name==='studio_business_capabilities')return config.capabilities??{data:{schemaVersion:1,foundation:true},error:null};return {data:{ok:true},error:null}}};const api=load('lib/studio/business/server.ts',{'../server':{authorize:async()=>({client}),databaseError:e=>new shared.StudioError(e.message??'Schema required','SCHEMA_REQUIRED',503)},'../contracts':shared,'./contracts':contracts});return {...api,calls}}
test('schema capability blocks mutation when absent or outdated',async()=>{for(const capabilities of[{data:null,error:{code:'PGRST202'}},{data:{schemaVersion:2,foundation:true},error:null},{data:{schemaVersion:1,foundation:false},error:null}]){const api=server({capabilities});await assert.rejects(()=>api.mutateBusiness(valid),e=>e.code==='SCHEMA_REQUIRED');assert.equal(api.calls.length,1)}});
test('reads and mutations use authenticated RPC after capability check',async()=>{const api=server();await api.mutateBusiness(valid);assert.deepEqual(api.calls.map(x=>x.name),['studio_business_capabilities','studio_business_mutate']);await api.readBusiness(new URLSearchParams({workspaceId:w,page:'2',view:'finals'}));assert.equal(api.calls[3].input.p_page,2);assert.equal(api.calls[3].input.p_view,'finals')});
test('read rejects invalid pagination',async()=>{const api=server();await assert.rejects(()=>api.readBusiness(new URLSearchParams({workspaceId:w,page:'NaN'})),e=>e.code==='VALIDATION');assert.equal(api.calls.length,1)});
