import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import React from 'react';import * as jsx from 'react/jsx-runtime';import {renderToStaticMarkup} from 'react-dom/server';
const root=new URL('../',import.meta.url),css=new Proxy({},{get:(_,key)=>String(key)});
function load(path,deps={}){const code=ts.transpileModule(fs.readFileSync(new URL(path,root),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const context={exports:{},URL,URLSearchParams,TextEncoder,crypto,fetch,AbortController,setTimeout,clearTimeout,require:k=>{if(k==='react')return React;if(k==='react/jsx-runtime')return jsx;if(k.endsWith('.module.css'))return {__esModule:true,default:css};if(k in deps)return deps[k];throw Error('Unknown '+k)}};vm.runInNewContext(code,context);return context.exports}
const shared=load('lib/studio/contracts.ts'),contracts=load('lib/studio/private-business/contracts.ts',{'../contracts':shared}),client=load('lib/studio/private-business/client.ts'),forms=load('components/studio/private-business/forms.tsx',{'../../../lib/studio/private-business/contracts':contracts,'../../../lib/studio/private-business/client':client}),board=load('components/studio/private-business/board.tsx',{'../../../lib/studio/private-business/contracts':contracts,'../../../lib/studio/private-business/client':client,'./forms':forms});
const id='10000000-0000-4000-8000-000000000001';const p={client:new client.PrivateBusinessClient(id,id),disabled:false,onSave:()=>{},onCancel:()=>{},onDirty:()=>{},onError:()=>{}};const record={id,workspace_id:id,book_id:id,kind:'budget',title:'Reviewable budget',notes:'Private local fixture only',owner_id:id,category:'Launch',counterparty:'',status:'active',amount_minor:'10025',currency:'USD',effective_date:'2026-10-02',due_date:null,renewal_date:null,notice_date:null,budget_id:null,commitment_id:null,document_version_id:null,approved_snapshot_id:null,signed_marked_at:null,signed_marked_by:null,revision:3,created_by:id,created_at:'2026-10-02',updated_at:'2026-10-02'};const render=(type,props)=>renderToStaticMarkup(React.createElement(type,props));
test('each record kind renders semantic form with real save controls',()=>{for(const kind of contracts.recordKinds){const html=render(forms.RecordForm,{...p,bookId:id,initialKind:kind});assert.match(html,/<form/);assert.match(html,/Create record/);assert.match(html,/Record owner/);assert.match(html,/does not grant access/);if(['budget','commitment','expense','income'].includes(kind))assert.match(html,/Amount/);if(kind==='contract')assert.match(html,/Marked signed/)} });
test('correction form displays previous values and mandatory reason',()=>{const html=render(forms.RecordForm,{...p,bookId:id,record});assert.match(html,/100.25/);assert.match(html,/Correction reason/);assert.match(html,/minLength="3"/);assert.match(html,/Save correction/)});
test('approval form renders exact amount revision and human checkbox',()=>{const html=render(forms.ApprovalForm,{...p,record});assert.match(html,/USD 100.25/);assert.match(html,/revision 3/);assert.match(html,/type="checkbox"/);assert.match(html,/does not authorize spending/);assert.match(html,/Approve plan snapshot/)});
test('version form labels unavailable uploads and permission-safe references',()=>{const html=render(forms.VersionForm,{...p,record:{...record,kind:'document'}});assert.match(html,/immutable HTTPS references/);assert.match(html,/uploads and file-byte snapshots are not available/);assert.match(html,/Do not paste credentials/);assert.doesNotMatch(html,/type="file"/)});
test('grant form uses explicit whole-register scope and required confirmation',()=>{const html=render(forms.GrantForm,{...p,book:{id,revision:0}});assert.match(html,/whole-register access/);assert.match(html,/every document, contract, finance record and history entry/);assert.match(html,/type="checkbox"/);assert.match(html,/Remove explicit access/)});
test('signed-out board has no synthetic private entries or editable actions',()=>{const html=render(board.PrivateBusinessBoard,{workspaceId:'',userId:''});assert.match(html,/Sign in and choose a workspace/);assert.doesNotMatch(html,/New register|Saved|100.25/)});
