import { requestOrigin } from './request-origin-test-loader.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const root=new URL('../',import.meta.url);function load(path,deps={}){const code=ts.transpileModule(fs.readFileSync(new URL(path,root),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const context={exports:{},Response,Request,URL,URLSearchParams,TextEncoder,crypto,require:k=>{if(!(k in deps))throw Error('Unexpected dependency: '+k);return deps[k]}};vm.runInNewContext(code,context);return context.exports}
const shared=load('lib/studio/contracts.ts'),contracts=load('lib/studio/private-business/contracts.ts',{'../contracts':shared}),w='10000000-0000-4000-8000-000000000001',r='20000000-0000-4000-8000-000000000001';const valid={workspaceId:w,expectedUserId:r,requestId:r,operation:'createBook',input:{title:'Private register'}},validate=contracts.validatePrivateMutation,invalid=x=>assert.throws(()=>validate(x),e=>e.code==='VALIDATION');
test('strict mutation envelope and identifiers',()=>{assert.equal(validate(valid).operation,'createBook');for(const x of [null,{...valid,workspaceId:'x'},{...valid,created_by:w},{...valid,operation:'constructor'},{...valid,input:{...valid.input,workspace_id:w}}])invalid(x)});
test('all mutations enforce identity and expected revision',()=>{for(const op of ['saveRecord','approveBudget','addDocumentVersion','updateBook','setGrant'])invalid({...valid,operation:op,input:{book_id:w,id:r}})});
test('money parses exact minor units without floating rounding',()=>{assert.equal(contracts.amountToMinor('0.29','USD'),'29');assert.equal(contracts.amountToMinor('123','JPY'),'123');assert.equal(contracts.amountToMinor('1.001','KWD'),'1001');assert.equal(contracts.minorToAmount('29','USD'),'0.29');assert.equal(contracts.minorToAmount('1001','KWD'),'1.001');for(const [v,c]of [['1.001','USD'],['1.1','JPY'],['-1','USD'],['1e3','USD'],['1,000','USD'],['90000000000.01','USD']])assert.throws(()=>contracts.amountToMinor(v,c),e=>e.code==='VALIDATION')});
test('record prevents forged grants actors approvals and unsupported currencies',()=>{const base={...valid,operation:'saveRecord',input:{book_id:w,record:{kind:'income',title:'Income',amount_minor:'50',currency:'USD',effective_date:'2026-10-01'}}};assert.equal(validate(base).operation,'saveRecord');for(const update of [{created_by:w},{approved_snapshot_id:w},{kind:'grant'},{amount_minor:50},{amount_minor:'1.1'},{currency:'XXX'},{effective_date:'2026-02-31'},{effective_date:'2026-99-99'}])invalid({...base,input:{...base.input,record:{...base.input.record,...update}}})});
test('HTTPS references reject active schemes credentials whitespace',()=>{contracts.validateHttpsReference('https://example.org/file.pdf');for(const x of ['javascript:alert(1)','http://example.org/x','https://user:password@example.org/x','https://example.org/a b','https://example.org/?token=secret','https://example.org/?X-Amz-Signature=secret','https://example.org/?%74oken=secret'])assert.throws(()=>contracts.validateHttpsReference(x),e=>e.code==='VALIDATION')});
function route(overrides={}){const calls=[];const api=load('app/api/studio/private-business/route.ts',{'@/lib/studio/request-origin':requestOrigin,'@/lib/studio/contracts':shared,'@/lib/studio/private-business/contracts':contracts,'@/lib/studio/private-business/server':{readPrivateBusiness:async params=>{calls.push({read:Object.fromEntries(params)});return {books:[]}},mutatePrivateBusiness:async payload=>{calls.push({write:payload});return {book:{id:w}}},...overrides}});return {...api,calls}}
const post=(value=valid,headers={})=>new Request('https://fairway.example/api/studio/private-business',{method:'POST',headers:{'content-type':'application/json',...headers},body:typeof value==='string'?value:JSON.stringify(value)});
test('read write and error responses cannot be cached or referred',async()=>{const api=route();for(const response of [await api.GET(new Request('https://fairway.example?workspaceId='+w+'&expectedUserId='+r)),await api.POST(post()),await api.POST(post('{bad'))]){assert.match(response.headers.get('cache-control'),/private, no-store/);assert.equal(response.headers.get('vary'),'Cookie');assert.equal(response.headers.get('referrer-policy'),'no-referrer')}});
test('cross-site writes are blocked before body or RPC',async()=>{const api=route();assert.equal((await api.POST(post(valid,{origin:'https://evil.example'}))).status,403);assert.equal((await api.POST(post(valid,{'sec-fetch-site':'cross-site'}))).status,403);assert.equal(api.calls.length,0)});
test('invalid JSON and byte-heavy content never reach mutation',async()=>{const api=route();assert.equal((await api.POST(post('{bad'))).status,422);assert.equal((await api.POST(post({...valid,input:{title:'💧'.repeat(10000)}}))).status,413);assert.equal(api.calls.length,0)});
test('private searches use body and never request URL',async()=>{const api=route();assert.equal((await api.GET(new Request('https://fairway.example?workspaceId='+w+'&expectedUserId='+r+'&q=secret'))).status,422);assert.equal(api.calls.length,0);const response=await api.POST(post({action:'read',workspaceId:w,expectedUserId:r,bookId:r,query:'secret supplier',page:2}));assert.equal(response.status,200);assert.equal(api.calls[0].read.q,'secret supplier');assert.equal(api.calls[0].read.page,'2');assert.equal((await response.json()).books.length,0)});
test('malicious read envelopes fail closed',async()=>{const api=route();for(const body of [{action:'other'},{action:'read',workspaceId:w,expectedUserId:r,table:'studio_requests'},{action:'read',workspaceId:w,expectedUserId:r,query:{sql:'x'}}])assert.equal((await api.POST(post(body))).status,422);assert.equal(api.calls.length,0)});
test('API returns canonical server result and hides unexpected failures',async()=>{const api=route();assert.equal((await(await api.POST(post())).json()).data.book.id,w);const bad=route({readPrivateBusiness:async()=>{throw Error('SQL secret credentials')}});const response=await bad.GET(new Request('https://fairway.example'));assert.equal(response.status,500);assert.ok(!JSON.stringify(await response.json()).includes('secret'))});
function server(config={}){const calls=[];let auths=0;const client={rpc:async(name,input)=>{calls.push({name,input});return name==='studio_private_business_capabilities'?(config.capabilities??{data:{schemaVersion:1,restrictedRecords:true},error:null}):(config.result??{data:{ok:true},error:null})}};const api=load('lib/studio/private-business/server.ts',{'../server':{authorize:async()=>{auths++;return {client,user:{id:r}}}},'../contracts':shared,'./contracts':contracts});return {...api,calls,auths:()=>auths}}
test('missing incompatible schema blocks all data calls',async()=>{for(const capabilities of[{data:null,error:{code:'PGRST202'}},{data:{schemaVersion:2,restrictedRecords:true},error:null},{data:{schemaVersion:1,restrictedRecords:false},error:null}]){const api=server({capabilities});await assert.rejects(()=>api.mutatePrivateBusiness(valid),e=>e.code==='SCHEMA_REQUIRED');assert.equal(api.calls.length,1)}});
test('every request reauthorizes and uses authenticated RPC',async()=>{const api=server();await api.mutatePrivateBusiness(valid);await api.readPrivateBusiness(new URLSearchParams({workspaceId:w,expectedUserId:r,bookId:r,page:'3'}));assert.equal(api.auths(),2);assert.equal(api.calls[1].name,'studio_private_business_mutate');assert.equal(api.calls[3].input.p_page,3)});
test('SQL errors never leak raw messages or parameters',async()=>{for(const [dbcode,code]of[['42501','FORBIDDEN'],['40001','CONFLICT'],['23514','VALIDATION'],['XX000','DATABASE_ERROR']]){const api=server({result:{data:null,error:{code:dbcode,message:'Private financial secret'}}});await assert.rejects(()=>api.mutatePrivateBusiness(valid),e=>e.code===code&&!e.message.includes('secret'))}});
test('invalid read UUIDs pagination rejected',async()=>{const api=server();for(const params of [{workspaceId:w,page:'NaN'},{workspaceId:w,page:'-1'},{workspaceId:w,recordId:'bad'},{workspaceId:w,recordId:r}])await assert.rejects(()=>api.readPrivateBusiness(new URLSearchParams({...params,expectedUserId:r})),e=>e.code==='VALIDATION')});
