import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';
import ts from 'typescript';
const context={exports:{},crypto:webcrypto,URL,URLSearchParams,Response,Error,fetch,AbortController,setTimeout,clearTimeout};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../lib/studio/private-business/client.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);
const {PrivateBusinessClient,PrivateBusinessError,createPrivateRequest,safePrivateUrl}=context.exports;
const workspace='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002';
const ok=data=>Response.json(data);const page={books:[],page:0,pageSize:50,total:0,asOf:'2026-10-03'};
const error=(status,code)=>Response.json({error:'Denied',code},{status});

test('deep frozen request envelope has a UUID and no shared input reference',()=>{const input={record:{title:'Original'}};const req=createPrivateRequest(workspace,id,'saveRecord',input);input.record.title='Changed';assert.equal(req.input.record.title,'Original');assert.match(req.requestId,/^[0-9a-f-]{36}$/);assert.equal(Object.isFrozen(req.input.record),true);assert.throws(()=>{req.input.record.title='Attempt'},TypeError)});
test('reads use no-store same-origin POST body, keeping search terms out of URL',async()=>{let seen;const client=new PrivateBusinessClient(workspace,id,async(url,init)=>{seen={url,init};return ok(page)});assert.equal((await client.read({q:'Private counterparty',page:0})).total,0);assert.equal(seen.url,'/api/studio/private-business');assert.equal(seen.init.method,'POST');assert.equal(seen.init.cache,'no-store');assert.equal(seen.init.credentials,'same-origin');assert.equal(seen.init.redirect,'error');assert.equal(seen.init.referrerPolicy,'no-referrer');assert.equal(JSON.parse(seen.init.body).query,'Private counterparty');assert.equal(JSON.parse(seen.init.body).action,'read')});
test('network-uncertain retry replays exact bytes and request ID',async()=>{const bodies=[];const client=new PrivateBusinessClient(workspace,id,async(_url,init)=>{bodies.push(init.body);if(bodies.length===1)throw new Error('offline');return ok({data:{book:{id}}})});await assert.rejects(client.mutate('createBook',{title:'Private'}),e=>e.uncertain===true);assert.equal(client.uncertain,true);assert.equal(client.pending,false);await assert.rejects(client.mutate('createBook',{title:'Another'}),e=>e.code==='REQUEST_PENDING');assert.equal(bodies.length,1);assert.equal((await client.retry()).book.id,id);assert.equal(bodies[0],bodies[1]);assert.equal(client.uncertain,false)});
test('duplicate clicks cannot issue concurrent writes',async()=>{let finish,calls=0;const client=new PrivateBusinessClient(workspace,id,()=>{calls++;return new Promise(resolve=>{finish=resolve})});const first=client.mutate('createBook',{title:'One'});assert.equal(client.pending,true);await assert.rejects(client.retry(),e=>e.code==='REQUEST_PENDING');await assert.rejects(client.mutate('createBook',{title:'Two'}),e=>e.code==='REQUEST_PENDING');finish(ok({data:{book:{id}}}));await first;assert.equal(calls,1)});
test('5xx writes remain uncertain and cannot be replaced',async()=>{const client=new PrivateBusinessClient(workspace,id,async()=>error(503,'DATABASE_ERROR'));await assert.rejects(client.mutate('createBook',{title:'One'}),e=>e.uncertain);assert.equal(client.uncertain,true)});
test('unreadable successful write retains same request for retry',async()=>{const bodies=[];const client=new PrivateBusinessClient(workspace,id,async(_url,init)=>{bodies.push(init.body);return bodies.length===1?new Response('broken',{status:200}):ok({data:{record:{id}}})});await assert.rejects(client.mutate('saveRecord',{title:'One'}),e=>e.uncertain);await client.retry();assert.equal(bodies[0],bodies[1])});
test('successful response missing confirmed record is uncertain',async()=>{const client=new PrivateBusinessClient(workspace,id,async()=>ok({data:{}}));await assert.rejects(client.mutate('createBook',{title:'One'}),e=>e.uncertain&&e.code==='INVALID_RESPONSE');assert.equal(client.uncertain,true)});
test('validation and revision conflicts release envelope for corrected request',async()=>{for(const status of [409,422]){const bodies=[];const client=new PrivateBusinessClient(workspace,id,async(_url,init)=>{bodies.push(init.body);return bodies.length===1?error(status,status===409?'CONFLICT':'VALIDATION'):ok({data:{book:{id}}})});await assert.rejects(client.mutate('createBook',{title:'One'}),e=>!e.uncertain);assert.equal(client.uncertain,false);await client.mutate('createBook',{title:'Corrected'});assert.notEqual(JSON.parse(bodies[0]).requestId,JSON.parse(bodies[1]).requestId)}});
test('schema failure is definite, fail-closed, and never queues a retry',async()=>{const client=new PrivateBusinessClient(workspace,id,async()=>error(503,'SCHEMA_REQUIRED'));await assert.rejects(client.mutate('createBook',{title:'One'}),e=>e.accessLost&&!e.uncertain);assert.equal(client.uncertain,false)});
test('permission loss on a read wipes the uncertain private mutation',async()=>{let calls=0;const client=new PrivateBusinessClient(workspace,id,async()=>{calls++;if(calls===1)throw new Error('offline');return error(403,'FORBIDDEN')});await assert.rejects(client.mutate('createBook',{title:'Secret'}));assert.equal(client.uncertain,true);await assert.rejects(client.read(),e=>e.accessLost);assert.equal(client.uncertain,false);await assert.rejects(client.retry(),e=>e.code==='REQUEST_PENDING');assert.equal(calls,2)});
test('unreadable unauthorized responses still wipe pending data',async()=>{let calls=0;const client=new PrivateBusinessClient(workspace,id,async()=>{calls++;if(calls===1)throw new Error('offline');return new Response('login required',{status:401})});await assert.rejects(client.mutate('createBook',{title:'Secret'}));await assert.rejects(client.read(),e=>e.accessLost);assert.equal(client.uncertain,false)});
test('late mutation success cannot revive a revoked session',async()=>{let finish;const client=new PrivateBusinessClient(workspace,id,()=>new Promise(resolve=>{finish=resolve}));const request=client.mutate('createBook',{title:'Secret'});client.clearAccess();finish(ok({data:{book:{id}}}));await assert.rejects(request,e=>e.accessLost);assert.equal(client.uncertain,false)});
test('late read cannot return private data after session revocation',async()=>{let finish;const client=new PrivateBusinessClient(workspace,id,()=>new Promise(resolve=>{finish=resolve}));const request=client.read();client.clearAccess();finish(ok(page));await assert.rejects(request,e=>e.accessLost)});
test('read responses require complete paging shape',async()=>{const client=new PrivateBusinessClient(workspace,id,async()=>ok({books:[]}));await assert.rejects(client.read(),e=>e.code==='INVALID_RESPONSE')});
test('document links reject active schemes and embedded credentials',()=>{assert.equal(safePrivateUrl('javascript:alert(1)'),null);assert.equal(safePrivateUrl('http://example.com'),null);assert.equal(safePrivateUrl('https://user:secret@example.com'),null);for(const url of ['https://example.com/?token=secret','https://example.com/?%74oken=secret','https://example.com/#access_token=secret','https://example.com/?X-Amz-Signature=secret','https://example.com/?X-Goog-Credential=secret'])assert.equal(safePrivateUrl(url),null);assert.equal(safePrivateUrl('https://example.com/doc?v=2'),'https://example.com/doc?v=2')});
test('board has privacy, lifecycle, manager scope and navigation safeguards',()=>{const board=fs.readFileSync(new URL('../components/studio/private-business/board.tsx',import.meta.url),'utf8');const forms=fs.readFileSync(new URL('../components/studio/private-business/forms.tsx',import.meta.url),'utf8');assert.match(board,/visibilitychange/);assert.match(board,/beforeunload/);assert.match(board,/onNavigationStateChange/);assert.match(board,/key=\{`\$\{props.workspaceId\}:\$\{props.userId/);assert.match(forms,/manual_budget_plan_only/);assert.match(forms,/whole register/);assert.match(forms,/does not grant access/);assert.match(forms,/uploads and file-byte snapshots are not available/);assert.doesNotMatch(board+forms,/localStorage\.|sessionStorage\.|useSWR|indexedDB|sendBeacon/)});

function componentModule(overrides={}) {
 let state=0;const saves=[];
 const react={useState(initial){const index=state++;return [Object.hasOwn(overrides,index)?overrides[index]:typeof initial==='function'?initial():initial,()=>{}]},useEffect(){},useId(){return 'field-id'}};
 function load(file,deps){const c={exports:{},URL,URLSearchParams,TextEncoder,BigInt,require(name){if(name in deps)return deps[name];throw new Error('Unexpected dependency: '+name)}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,c);return c.exports}
 const core=load('../lib/studio/contracts.ts',{});const contracts=load('../lib/studio/private-business/contracts.ts',{'../contracts':core});
 const ui=load('../components/studio/private-business/forms.tsx',{'react':react,'react/jsx-runtime':{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})},'../../../lib/studio/private-business/contracts':contracts,'../../../lib/studio/private-business/client':context.exports,'./private-business.module.css':{default:{}}});
 const props={client:{},disabled:false,onSave:(op,input)=>saves.push({op,input}),onCancel(){},onDirty(){},onError(){}};
 return {ui,props,saves};
}
test('new register form persists chosen public plan without copying data',()=>{const {ui,props,saves}=componentModule({0:'Private plan register',1:id});ui.BookForm(props).props.onSubmit({preventDefault(){}});assert.equal(saves[0].op,'createBook');assert.equal(saves[0].input.plan_id,id);assert.equal(saves[0].input.title,'Private plan register')});
test('register settings submit current revision',()=>{const {ui,props,saves}=componentModule({0:'Updated register',1:id});ui.BookForm({...props,book:{id,revision:4,title:'Old',plan_id:null}}).props.onSubmit({preventDefault(){}});assert.equal(saves[0].op,'updateBook');assert.equal(saves[0].input.expected_revision,4)});
test('document version form persists immutable HTTPS reference',()=>{const {ui,props,saves}=componentModule({0:'Signed version',1:'https://example.com/v/2'});ui.VersionForm({...props,record:{id,book_id:workspace,revision:2}}).props.onSubmit({preventDefault(){}});assert.equal(saves[0].op,'addDocumentVersion');assert.equal(saves[0].input.expected_revision,2);assert.equal(saves[0].input.url,'https://example.com/v/2')});
test('budget approval submits only explicitly confirmed planning purpose',()=>{const {ui,props,saves}=componentModule({0:'Reviewed plan',1:true});ui.ApprovalForm({...props,record:{id,book_id:workspace,revision:3,title:'Budget',amount_minor:'100000',currency:'USD'}}).props.onSubmit({preventDefault(){}});assert.equal(saves[0].op,'approveBudget');assert.equal(saves[0].input.purpose,'manual_budget_plan_only');assert.equal(saves[0].input.expected_revision,3)});
test('unconfirmed grant and budget approval do not submit',()=>{for(const name of ['GrantForm','ApprovalForm']){const {ui,props,saves}=componentModule();ui[name]({...props,book:{id,revision:0},record:{id,book_id:workspace,revision:0,title:'Budget',amount_minor:'100',currency:'USD'}}).props.onSubmit({preventDefault(){}});assert.equal(saves.length,0)}});
test('whole-register grants persist explicit member and permission',()=>{const {ui,props,saves}=componentModule({0:id,1:'none',2:true});ui.GrantForm({...props,book:{id:workspace,revision:8}}).props.onSubmit({preventDefault(){}});assert.equal(saves[0].op,'setGrant');assert.equal(saves[0].input.user_id,id);assert.equal(saves[0].input.permission,'none');assert.equal(saves[0].input.expected_revision,8)});
test('expense form preserves exact minor amounts and selected register relationships',()=>{const {ui,props,saves}=componentModule({1:'Paid invoice',7:'123.45',10:id,11:id,15:{effective_date:'2026-10-03',due_date:'',renewal_date:'',notice_date:''}});ui.RecordForm({...props,bookId:workspace,initialKind:'expense'}).props.onSubmit({preventDefault(){}});assert.equal(saves[0].op,'saveRecord');const r=saves[0].input.record;assert.equal(r.amount_minor,'12345');assert.equal(r.currency,'USD');assert.equal(r.budget_id,id);assert.equal(r.commitment_id,id);assert.equal(r.effective_date,'2026-10-03');assert.equal(saves[0].input.book_id,workspace)});

test('stalled write exits pending as uncertain and replays the original envelope',async()=>{const bodies=[];const client=new PrivateBusinessClient(workspace,id,async(_url,init)=>{bodies.push(init.body);if(bodies.length===1)return new Promise(()=>{});return ok({data:{book:{id}}})},5);await assert.rejects(client.mutate('createBook',{title:'One'}),e=>e.code==='TIMEOUT'&&e.uncertain);assert.equal(client.pending,false);assert.equal(client.uncertain,true);await client.retry();assert.equal(bodies[0],bodies[1])});
test('stalled response body also permits an exact uncertain retry',async()=>{let calls=0;const client=new PrivateBusinessClient(workspace,id,async()=>{calls++;return calls===1?{ok:true,status:200,json:()=>new Promise(()=>{})}:ok({data:{book:{id}}})},5);await assert.rejects(client.mutate('createBook',{title:'One'}),e=>e.code==='TIMEOUT');await client.retry();assert.equal(client.uncertain,false)});
test('selecting another document clears previously selected version',()=>{const forms=fs.readFileSync(new URL('../components/studio/private-business/forms.tsx',import.meta.url),'utf8');assert.match(forms,/setDocumentId\(v\);\s*setVersion\(''\)/)});
