import { requestOrigin } from './request-origin-test-loader.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
const root=new URL('../',import.meta.url);function load(path,deps={}){const code=ts.transpileModule(fs.readFileSync(new URL(path,root),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const context={exports:{},Response,Request,URL,URLSearchParams,TextEncoder,crypto,require:key=>{if(!(key in deps))throw Error('Unexpected dependency: '+key);return deps[key]}};vm.runInNewContext(code,context);return context.exports}
const shared=load('lib/studio/contracts.ts'),contracts=load('lib/studio/social/contracts.ts',{'../contracts':shared});const w='10000000-0000-4000-8000-000000000001',r='20000000-0000-4000-8000-000000000001';const valid={workspaceId:w,requestId:r,operation:'saveDraft',input:{title:'Content',channel:'instagram',account_label:'@fairway',format:'post',owner_id:w,timezone:'Etc/UTC',stage:'draft',assets:[]}};const invalid=x=>assert.throws(()=>contracts.validateSocialMutation(x),err=>err.code==='VALIDATION');
test('contract accepts identified draft envelope and rejects forged approval/identity',()=>{assert.equal(contracts.validateSocialMutation(valid).operation,'saveDraft');invalid(null);invalid({...valid,input:{state:'approved'}});invalid({...valid,input:{created_by:w}});invalid({...valid,actorId:w});invalid({...valid,operation:'publish'})});
test('existing mutations require post revisions, decisions require review revision',()=>{invalid({...valid,operation:'submitReview',input:{post_id:w,reviewers:[w]}});invalid({...valid,operation:'decideReview',input:{post_id:w,snapshot_id:r,expected_revision:0}});assert.equal(contracts.validateSocialMutation({...valid,operation:'decideReview',input:{post_id:w,snapshot_id:r,expected_review_revision:0}}).operation,'decideReview')});
function route(overrides={}){let reads=0,writes=0;const api=load('app/api/studio/social/route.ts',{'@/lib/studio/request-origin':requestOrigin,'@/lib/studio/contracts':shared,'@/lib/studio/social/contracts':contracts,'@/lib/studio/social/server':{readSocial:async()=>{reads++;return {kind:'data',data:{posts:[]}}},mutateSocial:async()=>{writes++;return {postId:w,revision:0}},...overrides}});return {...api,counts:()=>({reads,writes})}}
const post=(payload=valid,headers={})=>new Request('https://fairway.example/api/studio/social',{method:'POST',headers:{'content-type':'application/json',...headers},body:typeof payload==='string'?payload:JSON.stringify(payload)});
test('reads are private/no-store and no-referrer',async()=>{const api=route();const res=await api.GET(new Request('https://fairway.example'));assert.equal(res.status,200);assert.equal(res.headers.get('Cache-Control'),'private, no-store');assert.equal(res.headers.get('Referrer-Policy'),'no-referrer');assert.equal(res.headers.get('Vary'),'Cookie')});
test('mutation blocks CSRF before execution',async()=>{const api=route();assert.equal((await api.POST(post(valid,{origin:'https://evil.example'}))).status,403);assert.equal((await api.POST(post(valid,{'sec-fetch-site':'cross-site'}))).status,403);assert.equal(api.counts().writes,0)});
test('invalid JSON and large Unicode body never mutate',async()=>{const api=route();assert.equal((await api.POST(post('{bad'))).status,400);assert.equal((await api.POST(post({...valid,input:{caption:'💧'.repeat(18000)}}))).status,413);assert.equal(api.counts().writes,0)});
test('POST success requires canonical persisted result',async()=>{const api=route();const res=await api.POST(post());assert.equal((await res.json()).data.postId,w);assert.equal(api.counts().writes,1)});
test('errors preserve actionable status without private SQL leaks',async()=>{for(const [code,status] of [['CONFLICT',409],['FORBIDDEN',403],['SCHEMA_REQUIRED',503]]){const res=await route({mutateSocial:async()=>{throw new shared.StudioError('Fixture',code,status)}}).POST(post());assert.equal(res.status,status);assert.equal((await res.json()).code,code)}const res=await route({readSocial:async()=>{throw Error('SQL PASSWORD')}}).GET(new Request('https://fairway.example'));assert.equal(res.status,500);assert.doesNotMatch(JSON.stringify(await res.json()),/SQL|PASSWORD/)});
test('manual manifest is attached with no cache; download redirect uses only exact authenticated version',async()=>{const manifest={kind:'manual_publication_package',caption:'Approved'};const api=route({readSocial:async()=>({kind:'package',data:manifest})});const res=await api.GET(new Request('https://fairway.example'));assert.match(res.headers.get('Content-Disposition'),/attachment/);assert.deepEqual(await res.json(),manifest);const asset=await route({readSocial:async()=>({kind:'asset',versionId:r})}).GET(new Request('https://fairway.example'));assert.equal(asset.status,307);assert.equal(asset.headers.get('Location'),`/api/studio/media?versionId=${r}&download=1`);assert.equal(asset.headers.get('Cache-Control'),'private, no-store')});
function server(config={}){const calls=[];const client={rpc:async(name,input)=>{calls.push({name,input});if(name==='studio_social_capabilities')return config.capabilities??{data:{schemaVersion:1,manualPackages:true},error:null};return config.reply??{data:{ok:true},error:null}}};const api=load('lib/studio/social/server.ts',{'../server':{authorize:async()=>({client}),databaseError:e=>new shared.StudioError(e.message??'Setup required','SCHEMA_REQUIRED',503)},'../contracts':shared,'./contracts':contracts});return {...api,calls}}
test('capability fails closed for missing/outdated schema',async()=>{for(const capabilities of[{data:null,error:{code:'PGRST202'}},{data:{schemaVersion:2,manualPackages:true}},{data:{schemaVersion:1,manualPackages:false}}]){const api=server({capabilities});await assert.rejects(()=>api.mutateSocial(valid),e=>e.code==='SCHEMA_REQUIRED');assert.equal(api.calls.length,1)}});
test('read and write call only current-user RPCs, with precise workspace/page',async()=>{const api=server();await api.mutateSocial(valid);await api.readSocial(new URLSearchParams({workspaceId:w,page:'2',options:'1'}));assert.deepEqual(api.calls.map(x=>x.name),['studio_social_capabilities','studio_social_mutate','studio_social_capabilities','studio_social_read']);assert.equal(api.calls[3].input.p_page,2);assert.equal(api.calls[3].input.p_options,true)});
test('invalid pagination, asset indices and IDs fail before data RPC',async()=>{for(const q of [{page:'-1'},{postId:'bad'},{snapshotId:r,asset:'-1'},{package:'bad'}]){const api=server();await assert.rejects(()=>api.readSocial(new URLSearchParams({workspaceId:w,...q})),e=>e.code==='VALIDATION');assert.equal(api.calls.length,1)}});
test('download and export route call purpose-specific authorization RPC first',async()=>{const api=server({reply:{data:r,error:null}});const asset=await api.readSocial(new URLSearchParams({workspaceId:w,snapshotId:r,asset:'0'}));assert.equal(asset.versionId,r);assert.equal(api.calls[1].name,'studio_social_asset');const bad=server({reply:{data:'https://storage/private',error:null}});await assert.rejects(()=>bad.readSocial(new URLSearchParams({workspaceId:w,snapshotId:r,asset:'0'})),e=>e.code==='DATABASE_ERROR')});
