'use client';
import { useEffect, useRef, useState } from 'react';
import type { SocialDraft, SocialList } from '../../../lib/studio/social/contracts';
import { asSocialError, readSocialList, SocialApiError } from '../../../lib/studio/social/client';
import { SocialCalendar } from './calendar';
import { SocialContentDetail } from './detail';
import { SocialEditor } from './editor';
import { Badge, dateLabel, Empty, ErrorState, mayLeave, memberName, MutationFeedback, stateLabel, useLeaveWarning, useSocialMutation, useSocialNavigationState, type SocialNavigationState } from './ui';
import styles from './social.module.css';
export type SocialBoardProps={workspaceId:string;externalNavigationGuard?:boolean;initialView?:'board'|'calendar'|'feedback';initialPostId?:string;onRouteChange?:(view:'board'|'calendar'|'feedback',postId:string|null)=>boolean;onOpenTask?:(id:string)=>void;onOpenProject?:(id:string)=>void;onOpenFile?:(id:string)=>void;onChanged?:()=>void;onNavigationStateChange?:(state:SocialNavigationState)=>void};
export function SocialBoard(props:SocialBoardProps){return <SocialWorkspace key={props.workspaceId} {...props}/>;}
export default SocialBoard;
function SocialWorkspace({workspaceId,externalNavigationGuard,initialView='board',initialPostId,onRouteChange,onOpenTask,onOpenProject,onOpenFile,onChanged,onNavigationStateChange}:SocialBoardProps) {
 const [data,setData]=useState<SocialList|null>(null),[calendar,setCalendar]=useState<SocialDraft[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<SocialApiError|null>(null),[page,setPage]=useState(0),[view,setView]=useState<'board'|'calendar'|'feedback'>(initialView),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState<string|null>(initialPostId||null),[creating,setCreating]=useState(false),[dirty,setDirty]=useState(false),[detailNavigation,setDetailNavigation]=useState<SocialNavigationState>({dirty:false,pending:false,uncertain:false});
 const changedRef=useRef(onChanged);useEffect(()=>{changedRef.current=onChanged;},[onChanged]);
 function changed(){setLoading(true);setRefresh(v=>v+1);changedRef.current?.();}
 const mutation=useSocialMutation(workspaceId,changed),disabled=loading||Boolean(error)||mutation.blocked;
 useSocialNavigationState(selected?detailNavigation:{dirty,pending:mutation.busy,uncertain:Boolean(mutation.error?.uncertain)},onNavigationStateChange);
 useLeaveWarning(!externalNavigationGuard&&!selected&&(dirty||mutation.busy||Boolean(mutation.error?.uncertain)));
 const lastRoute=useRef(JSON.stringify([initialView,initialPostId||null]));
 useEffect(()=>{const next=JSON.stringify([view,selected]);if(next!==lastRoute.current&&!mutation.busy&&!mutation.error?.uncertain&&!detailNavigation.pending&&!detailNavigation.uncertain){if(!onRouteChange||onRouteChange(view,selected))lastRoute.current=next;}},[view,selected,mutation.busy,mutation.error?.uncertain,detailNavigation.pending,detailNavigation.uncertain,onRouteChange]);
 useEffect(()=>{if(!workspaceId){setLoading(false);return;}const controller=new AbortController();setLoading(true);setError(null);void(async()=>{try{const first=await readSocialList(workspaceId,view==='calendar'?0:page,controller.signal);if(controller.signal.aborted)return;
 if(view==='calendar'){const rows=[...first.posts];for(let next=1;next<Math.ceil(first.total/first.pageSize);next++){const result=await readSocialList(workspaceId,next,controller.signal);if(controller.signal.aborted)return;if(result.total!==first.total)throw new SocialApiError('Content changed while loading the calendar. Refresh for a consistent weekly view.','CONFLICT',409);rows.push(...result.posts);}if(new Set(rows.map(p=>p.id)).size!==first.total)throw new SocialApiError('The full calendar could not be loaded. Refresh to try again.','INCOMPLETE',502);setCalendar(rows);}
 else if(page>=Math.max(1,Math.ceil(first.total/first.pageSize))){setPage(Math.max(0,Math.ceil(first.total/first.pageSize)-1));return;}setData(first);
 }catch(cause){if(!controller.signal.aborted){const issue=asSocialError(cause);setError(issue);if(issue.unavailable){setData(null);setCalendar([]);}}}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[workspaceId,page,view,refresh]);
 function closeCreate(){if(mayLeave(dirty,mutation.blocked)){setDirty(false);setCreating(false);}}
 if(!workspaceId)return <section className={styles.root}><Empty title="Choose a connected workspace">Sign in and select a workspace to plan and review real social content.</Empty></section>;
 if(selected&&data)return <section className={styles.root}><SocialContentDetail externalNavigationGuard={externalNavigationGuard} key={selected} workspaceId={workspaceId} postId={selected} members={data.members} actorId={data.actorId} onBack={()=>{setSelected(null);setDetailNavigation({dirty:false,pending:false,uncertain:false});}} onChanged={changed} onOpenTask={onOpenTask} onOpenProject={onOpenProject} onOpenFile={onOpenFile} onNavigationStateChange={setDetailNavigation}/></section>;
 const pageCount=data?Math.max(1,Math.ceil(data.total/data.pageSize)):1;
 return <section className={styles.root} aria-label="Social content board"><header className={styles.header}><div><p className={styles.eyebrow}>Fairway Studio</p><h1>Social</h1><p className={styles.muted}>A considered path from source to story, publication and learning.</p></div><div className={styles.row}><button className={styles.button} disabled={loading||mutation.blocked} onClick={()=>setRefresh(v=>v+1)}>Refresh</button><button className={styles.primary} disabled={disabled||creating||!data} onClick={()=>{setCreating(true);setDirty(false);}}>New content idea</button></div></header><MutationFeedback mutation={mutation} onRefresh={()=>setRefresh(v=>v+1)}/>{error?<ErrorState error={error} retry={()=>setRefresh(v=>v+1)}/>:null}{loading?<p className={styles.muted} role="status">Loading saved social content…</p>:null}
 {creating&&data?<section className={styles.panel}><SocialEditor workspaceId={workspaceId} members={data.members} actorId={data.actorId} disabled={disabled} onDirty={setDirty} onCancel={closeCreate} onSave={input=>mutation.mutate('saveDraft',input,'Content draft saved.',result=>{setCreating(false);setDirty(false);setSelected(result.postId);})}/></section>:null}
 <nav className={styles.tabs} aria-label="Social views">{([{value:'board',title:'Content Board'},{value:'calendar',title:'Calendar'},{value:'feedback',title:'Feedback'}] as const).map(tab=><button key={tab.value} className={styles.tab} aria-pressed={view===tab.value} disabled={mutation.blocked||creating} onClick={()=>{setView(tab.value);setPage(0);}}>{tab.title}</button>)}</nav>
 {data&&!error&&!loading?<>{view==='calendar'?<SocialCalendar posts={calendar} disabled={disabled||creating} onOpen={setSelected}/>:<><div className={styles.header}><div><h2>{view==='feedback'?'Feedback by content':'Ideas, drafts and publication packages'}</h2><p className={styles.muted}>{view==='feedback'?'Open content to record real observations, optional manual metrics and a human-chosen creative task.':'Workspace-visible content. Separate publication review is required for each exact package.'}</p></div><span className={styles.small}>{data.total} saved record{data.total===1?'':'s'}</span></div>{data.posts.length?<div className={styles.grid}>{data.posts.map(post=><button className={styles.cardButton} key={post.id} disabled={disabled||creating} onClick={()=>setSelected(post.id)} aria-label={`Open ${post.title}`}><div className={styles.row}><Badge tone={post.state}>{stateLabel(post.state)}</Badge><Badge>{post.channel}</Badge></div><h3 style={{marginTop:14}}>{post.title}</h3><p className={styles.muted}>{post.caption?`${post.caption.slice(0,180)}${post.caption.length>180?'…':''}`:'No caption yet.'}</p><div className={styles.metadata}><span>{memberName(data.members,post.owner_id)}</span><span>Replies: {memberName(data.members,post.reply_owner_id)}</span><span>{dateLabel(post.planned_at,post.timezone)} ({post.timezone})</span></div>{view==='feedback'?<p className={styles.small} style={{marginTop:12}}>Open saved observations and manual metrics</p>:null}</button>)}</div>:<Empty title="Your next story starts here">Capture a real idea, choose a cleared part of the process, ask one focused question, then return with what changed. No sample posts or invented metrics are added.</Empty>}<div className={styles.toolbar} style={{marginTop:22}}><button className={styles.button} disabled={disabled||creating||page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span className={styles.small}>Page {page+1} of {pageCount}</span><button className={styles.button} disabled={disabled||creating||page>=pageCount-1} onClick={()=>setPage(p=>p+1)}>Next</button></div></> }<p className={styles.small} style={{marginTop:20}}>Manual planning and publication records only. No automatic posting, scheduler, social OAuth or synced audience metrics.</p></>:null}
 </section>;
}
