'use client';
import { useState } from 'react';
import type { SocialDraft } from '../../../lib/studio/social/contracts';
import { Badge, dateLabel, stateLabel } from './ui';
import styles from './social.module.css';
export function calendarDate(instant:string,timezone:string) {const parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(instant));const fields=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${fields.year}-${fields.month}-${fields.day}`;}
function weekStart(){const day=new Date();day.setUTCHours(12,0,0,0);day.setUTCDate(day.getUTCDate()-((day.getUTCDay()+6)%7));return day.toISOString().slice(0,10);}
export function SocialCalendar({posts,disabled,onOpen}:{posts:SocialDraft[];disabled:boolean;onOpen:(id:string)=>void}) {
 const [start,setStart]=useState(weekStart),[timezone,setTimezone]=useState('UTC'),[zoneInput,setZoneInput]=useState('UTC'),[issue,setIssue]=useState(''),[format,setFormat]=useState('all');
 function shift(days:number){const date=new Date(`${start}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);setStart(date.toISOString().slice(0,10));}
 const dates=Array.from({length:7},(_,i)=>{const date=new Date(`${start}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+i);return date.toISOString().slice(0,10);});
 const active=posts.filter(p=>p.state!=='archived'&&(format==='all'||p.format===format));
 const unplanned=active.filter(p=>!p.planned_at);
 return <section><div className={styles.header}><div><h2>Weekly content batch</h2><p className={styles.muted}>All saved content across this workspace. Dates are plans, not an external posting schedule.</p></div><div className={styles.row}><button className={styles.button} disabled={disabled} onClick={()=>shift(-7)}>Previous week</button><button className={styles.button} disabled={disabled} onClick={()=>setStart(weekStart())}>This week</button><button className={styles.button} disabled={disabled} onClick={()=>shift(7)}>Next week</button></div></div><label className={styles.field} style={{maxWidth:260,marginBottom:16}}>Weekly queue format<select value={format} disabled={disabled} onChange={e=>setFormat(e.target.value)}><option value="all">All formats</option><option value="story">Stories</option><option value="post">Posts</option><option value="reel">Reels</option><option value="video">Videos</option></select></label><form className={styles.row} onSubmit={e=>{e.preventDefault();try{new Intl.DateTimeFormat('en',{timeZone:zoneInput});setTimezone(zoneInput);setIssue('');}catch{setIssue('Enter a valid IANA timezone.');}}}><label className={styles.field}>Calendar display timezone<input value={zoneInput} onChange={e=>setZoneInput(e.target.value)} disabled={disabled}/></label><button className={styles.button} disabled={disabled}>Apply timezone</button><p className={styles.small}>Viewing {timezone}. Each card also shows its saved posting timezone.</p></form>{issue?<p className={styles.error} role="alert">{issue}</p>:null}<div className={styles.calendar} style={{marginTop:18}}>{dates.map(date=>{const items=active.filter(p=>p.planned_at&&calendarDate(p.planned_at,timezone)===date);return <section className={styles.day} key={date}><h3>{new Date(`${date}T12:00:00Z`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'})}</h3>{items.length?items.map(post=><button className={styles.cardButton} key={post.id} disabled={disabled} onClick={()=>onOpen(post.id)}><Badge tone={post.state}>{stateLabel(post.state)}</Badge><h3 style={{marginTop:8}}>{post.title}</h3><p className={styles.small}>{post.channel} · {post.account_label||'No account'} · {post.format}</p><p className={styles.small}>{dateLabel(post.planned_at,post.timezone)} ({post.timezone})</p></button>):<p className={styles.small}>Nothing planned</p>}</section>;})}</div>{unplanned.length?<section className={styles.panel} style={{marginTop:18}}><h3>Unplanned content ({unplanned.length})</h3><div className={styles.row}>{unplanned.map(post=><button className={styles.button} key={post.id} disabled={disabled} onClick={()=>onOpen(post.id)}>{post.title}</button>)}</div></section>:null}</section>;
}
