'use client';
import { useEffect, useRef, useState } from 'react';
import type { SocialDetail, SocialDraft, SocialMember } from '../../../lib/studio/social/contracts';
import { asSocialError, readSocialDetail, safeSocialUrl, type SocialApiError } from '../../../lib/studio/social/client';
import { SocialEditor } from './editor';
import { FeedbackForm, FeedbackList, FeedbackTaskForm } from './feedback';
import { ManualPackage, PublicationForm } from './publication';
import { ReviewDecision, ReviewSubmit, SnapshotHistory } from './review';
import { Badge, dateLabel, ErrorState, mayLeave, memberName, MutationFeedback, stateLabel, useLeaveWarning, useSocialMutation, useSocialNavigationState, type SocialNavigationState } from './ui';
import styles from './social.module.css';
type Mode='view'|'edit'|'submit'|'decide'|'publish'|'feedback'|'task';
export function SocialContentDetail({externalNavigationGuard,workspaceId,postId,members,actorId,onBack,onChanged,onOpenTask,onOpenProject,onOpenFile,onNavigationStateChange}:{externalNavigationGuard?:boolean;workspaceId:string;postId:string;members:SocialMember[];actorId:string;onBack:()=>void;onChanged:()=>void;onOpenTask?:(id:string)=>void;onOpenProject?:(id:string)=>void;onOpenFile?:(id:string)=>void;onNavigationStateChange?:(state:SocialNavigationState)=>void}) {
 const [data,setData]=useState<SocialDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<SocialApiError|null>(null),[refresh,setRefresh]=useState(0),[mode,setMode]=useState<Mode>('view'),[dirty,setDirty]=useState(false),[editingPost,setEditingPost]=useState<SocialDraft|undefined>(),[editorKey,setEditorKey]=useState(0),[feedbackId,setFeedbackId]=useState<string|null>(null),[formData,setFormData]=useState<SocialDetail|null>(null);
 const dirtyRef=useRef(false);function markDirty(value:boolean){dirtyRef.current=value;setDirty(value);}
 function refreshSaved(){setLoading(true);setRefresh(v=>v+1);}
 const mutation=useSocialMutation(workspaceId,()=>{refreshSaved();onChanged();});
 const blocked=mutation.blocked,disabled=blocked||loading||Boolean(error);
 useSocialNavigationState({dirty,pending:mutation.busy,uncertain:Boolean(mutation.error?.uncertain)},onNavigationStateChange);
 useLeaveWarning(!externalNavigationGuard&&(dirty||mutation.busy||Boolean(mutation.error?.uncertain)));
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);void readSocialDetail(workspaceId,postId,controller.signal).then(value=>{if(!controller.signal.aborted)setData(value);}).catch(cause=>{if(!controller.signal.aborted){const issue=asSocialError(cause);setError(issue);if(issue.unavailable)setData(null);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[workspaceId,postId,refresh]);
 function closeForm(){if(mayLeave(dirtyRef.current,blocked)){markDirty(false);setMode('view');setFeedbackId(null);}}
 function open(next:Mode,id:string|null=null){if(disabled||!mayLeave(dirtyRef.current,blocked))return;markDirty(false);setFeedbackId(id);setFormData(data);if(next==='edit'){setEditingPost(data?.post);setEditorKey(v=>v+1);}setMode(next);}
 const snapshot=data?.snapshots.find(s=>s.id===data.post.approved_snapshot_id);
 const currentReview=data?.reviews.find(r=>r.state==='open');
 const reviewSnapshot=data?.snapshots.find(s=>s.id===currentReview?.snapshot_id);
 const myDecision=data?.decisions.some(d=>d.snapshot_id===currentReview?.snapshot_id&&d.reviewer_id===actorId);
 const actionData=formData||data;
 const actionReview=actionData?.reviews.find(r=>r.state==='open');
 const actionReviewSnapshot=actionData?.snapshots.find(s=>s.id===actionReview?.snapshot_id);
 const actionSnapshot=actionData?.snapshots.find(s=>s.id===actionData.post.approved_snapshot_id);
 const feedback=actionData?.feedback.find(f=>f.id===feedbackId);
 return <div><header className={styles.header}><button className={styles.button} disabled={blocked} onClick={()=>{if(mayLeave(dirtyRef.current,blocked))onBack();}}>Back to Social</button><button className={styles.button} disabled={blocked||loading} onClick={refreshSaved}>Refresh saved content</button></header><MutationFeedback mutation={mutation} onRefresh={refreshSaved}/>{error?<ErrorState error={error} retry={refreshSaved}/>:null}{loading?<p className={styles.muted} role="status">Loading saved content…</p>:null}
 {data?<><header className={styles.header}><div><p className={styles.eyebrow}>Social content · revision {data.post.revision}</p><h1>{data.post.title}</h1><div className={styles.row}><Badge tone={data.post.state}>{stateLabel(data.post.state)}</Badge><span className={styles.small}>Workspace visible · {memberName(members,data.post.owner_id)}</span></div></div></header>
 {mode==='edit'?<section className={styles.panel}><SocialEditor key={editorKey} workspaceId={workspaceId} post={editingPost} currentRevision={data.post.revision} members={members} actorId={actorId} disabled={disabled} onDirty={markDirty} onCancel={closeForm} onReload={()=>{if(mayLeave(dirtyRef.current,blocked)){setEditingPost(data.post);setEditorKey(v=>v+1);markDirty(false);}}} onSave={input=>mutation.mutate('saveDraft',input,'Working draft saved. Publication approval requires a separate review.',()=>{markDirty(false);setMode('view');})}/></section>:null}
 {mode==='submit'?<section className={styles.panel}><ReviewSubmit detail={actionData!} members={members} mutation={mutation} disabled={disabled} onDirty={markDirty} onCancel={closeForm}/></section>:null}
 {mode==='decide'&&actionReview&&actionReviewSnapshot?<section className={styles.panel}><ReviewDecision detail={actionData!} snapshot={actionReviewSnapshot} review={actionReview} members={members} mutation={mutation} disabled={disabled} onDirty={markDirty} onCancel={closeForm}/></section>:null}
 {mode==='publish'&&actionSnapshot?<section className={styles.panel}><PublicationForm detail={actionData!} snapshot={actionSnapshot} mutation={mutation} disabled={disabled} onDirty={markDirty} onCancel={closeForm}/></section>:null}
 {mode==='feedback'?<section className={styles.panel}><FeedbackForm key={feedbackId||'new'} detail={actionData!} feedback={feedback} members={members} actorId={actorId} mutation={mutation} disabled={disabled} onDirty={markDirty} onCancel={closeForm}/></section>:null}
 {mode==='task'&&feedback?<section className={styles.panel}><FeedbackTaskForm detail={actionData!} feedback={feedback} mutation={mutation} disabled={disabled} onDirty={markDirty} onCancel={closeForm}/></section>:null}
 {mode!=='view'?<p className={styles.muted}>Finish or close this form to return to the content history.</p>:<><section className={styles.panel}><div className={styles.toolbar}>{data.post.state!=='archived'?<button className={styles.primary} disabled={disabled} onClick={()=>open('edit')}>Edit working draft</button>:null}{['idea','draft'].includes(data.post.state)?<button className={styles.button} disabled={disabled} onClick={()=>open('submit')}>Request publication review</button>:null}{currentReview&&reviewSnapshot?.reviewers.includes(actorId)&&!myDecision?<button className={styles.primary} disabled={disabled} onClick={()=>open('decide')}>Review exact package</button>:null}{snapshot&&data.post.state==='approved'?<button className={styles.button} disabled={disabled} onClick={()=>open('publish')}>Mark as manually posted</button>:null}{data.publications.length?<button className={styles.button} disabled={disabled} onClick={()=>open('feedback')}>Record feedback</button>:null}{['idea','draft'].includes(data.post.state)?<button className={styles.danger} disabled={disabled} onClick={()=>{if(window.confirm('Archive this saved draft? It will remain in the workspace history.'))mutation.mutate('archiveDraft',{post_id:data.post.id,expected_revision:data.post.revision},'Draft archived.');}}>Archive draft</button>:null}</div><div className={styles.metadata}><span>{data.post.channel} · {data.post.account_label||'No account chosen'} · {data.post.format}</span><span>Replies: {memberName(members,data.post.reply_owner_id)}</span><span>Planned: {dateLabel(data.post.planned_at,data.post.timezone)} ({data.post.timezone})</span></div><h2 style={{marginTop:22}}>Working caption</h2><p className={styles.caption}>{data.post.caption||'No caption yet.'}</p><p className={styles.prose}>Purpose: {data.post.purpose||'Not recorded'}<br/>Audience: {data.post.audience||'Not recorded'}<br/>Release constraints: {data.post.release_note||'None recorded'}</p>{data.post.project_id&&onOpenProject?<button className={styles.button} disabled={disabled} onClick={()=>onOpenProject(data.post.project_id!)}>Open source project</button>:null}<p className={styles.small}>Exact source version: {data.post.source_version_id||'Not selected'}</p>{data.post.embargo_until?<p className={styles.notice}>Embargo until {dateLabel(data.post.embargo_until,data.post.timezone)} ({data.post.timezone}). Package downloads are checked against the embargo on every request.</p>:null}<p className={styles.small}>Planned times are not scheduled. There is no external scheduler, automatic posting, social account connection or metrics sync.</p></section>
 {snapshot&&['approved','posted'].includes(data.post.state)?<ManualPackage key={snapshot.id} workspaceId={workspaceId} snapshot={snapshot} disabled={disabled}/>:null}
 <section className={styles.panel}><h2>Manually recorded publications</h2>{data.publications.length?<ul className={styles.list}>{data.publications.map(item=><li key={item.id}><Badge>Manually recorded · not platform-verified</Badge><p className={styles.muted}>{dateLabel(item.posted_at,data.post.timezone)} · recorded by {memberName(members,item.recorded_by)}</p>{safeSocialUrl(item.url)?<a className={styles.link} href={safeSocialUrl(item.url)!} rel="noopener noreferrer" target="_blank">{item.url}</a>:<p>Invalid saved URL</p>}<p className={styles.small}>Approved snapshot {data.snapshots.find(s=>s.id===item.snapshot_id)?.ordinal||item.snapshot_id}</p></li>)}</ul>:<p className={styles.muted}>No actual publication has been recorded.</p>}</section>
 <FeedbackList detail={data} members={members} disabled={disabled} onEdit={id=>open('feedback',id)} onTask={id=>open('task',id)} onOpenTask={onOpenTask}/><SnapshotHistory detail={data} members={members} onOpenFile={disabled?undefined:onOpenFile}/>
 </>}
 </>:null}</div>;
}
