'use client';
import { useState } from 'react';
import type { AssetClearance, Channel, SocialDraft, SocialMember } from '../../../lib/studio/social/contracts';
import { instantFromWall, safeSocialUrl, wallTime } from '../../../lib/studio/social/client';
import { MemberSelect } from './ui';
import { SourcePicker } from './source-picker';
import styles from './social.module.css';
export type DraftFields = {title:string;purpose:string;audience:string;channel:Channel;account_label:string;caption:string;format:SocialDraft['format'];owner_id:string;reply_owner_id:string;idea_id:string;project_id:string;source_version_id:string;planned_at:string;timezone:string;embargo_until:string;release_note:string;assets:AssetClearance[];stage:'idea'|'draft'};
export function draftFields(post:SocialDraft|undefined,actorId:string):DraftFields {
 const timezone=post?.timezone||'UTC';
 return {title:post?.title||'',purpose:post?.purpose||'',audience:post?.audience||'',channel:post?.channel||'instagram',account_label:post?.account_label||'',caption:post?.caption||'',format:post?.format||'post',owner_id:post?.owner_id||actorId,reply_owner_id:post?.reply_owner_id||'',idea_id:post?.idea_id||'',project_id:post?.project_id||'',source_version_id:post?.source_version_id||'',planned_at:wallTime(post?.planned_at||null,timezone),timezone,embargo_until:wallTime(post?.embargo_until||null,timezone),release_note:post?.release_note||'',assets:post?.assets.map(a=>({version_id:a.version_id,rights:a.rights,rights_note:a.rights_note,consent_confirmed:a.consent_confirmed,attribution:a.attribution,public_link:a.public_link}))||[],stage:post?.state==='idea'?'idea':'draft'};
}
export function draftInput(fields:DraftFields,post?:SocialDraft):Record<string,unknown> {
 const planned=instantFromWall(fields.planned_at,fields.timezone),embargo=instantFromWall(fields.embargo_until,fields.timezone);
 try{new Intl.DateTimeFormat('en',{timeZone:fields.timezone});}catch{throw new Error('Enter a valid IANA timezone.');}
 if(!fields.title.trim()||!fields.owner_id||!fields.account_label.trim())throw new Error('Choose a title, current owner and destination account label.');
 if(new Set(fields.assets.map(a=>a.version_id)).size!==fields.assets.length)throw new Error('Select each media version only once.');
 if(fields.assets.some(a=>!a.version_id))throw new Error('Choose an exact version for every media item, or remove the empty item.');
 if(fields.assets.some(a=>a.public_link&&(!safeSocialUrl(a.public_link)||new URL(a.public_link).search||/\/storage\/v1\/object\/sign\//i.test(new URL(a.public_link).pathname))))throw new Error('Use a clean public HTTPS media link with no query string, signed storage path or access token.');
 return {...fields,...(post?{post_id:post.id,expected_revision:post.revision}:{}),title:fields.title.trim(),reply_owner_id:fields.reply_owner_id||null,idea_id:fields.idea_id||null,project_id:fields.project_id||null,source_version_id:fields.source_version_id||null,planned_at:planned,embargo_until:embargo,assets:fields.assets.map(a=>({version_id:a.version_id,rights:a.rights,rights_note:a.rights_note,consent_confirmed:a.consent_confirmed,attribution:a.attribution,public_link:a.public_link?.trim()||null}))};
}
export function SocialEditor({workspaceId,post,currentRevision,members,actorId,disabled,onDirty,onSave,onCancel,onReload}:{workspaceId:string;post?:SocialDraft;currentRevision?:number;members:SocialMember[];actorId:string;disabled:boolean;onDirty:(dirty:boolean)=>void;onSave:(input:Record<string,unknown>)=>void;onCancel:()=>void;onReload?:()=>void}) {
 const [fields,setFields]=useState(()=>draftFields(post,actorId)),[issue,setIssue]=useState('');
 function set<K extends keyof DraftFields>(key:K,value:DraftFields[K]){setFields(old=>({...old,[key]:value}));onDirty(true);}
 function asset(index:number,patch:Partial<AssetClearance>){set('assets',fields.assets.map((item,i)=>i===index?{...item,...patch}:item));}
 const stale=post&&currentRevision!==undefined&&post.revision!==currentRevision;
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();setIssue('');try{if(stale)throw new Error('Reload the latest saved version before saving this outdated draft.');onSave(draftInput(fields,post));}catch(cause){setIssue(cause instanceof Error?cause.message:'Check your draft.');}}}>
  <div className={styles.spread}><div><h2>{post?'Edit working draft':'Capture an idea or draft'}</h2><p className={styles.muted}>Your changes remain in memory until saved. Editing approved content requires a new publication review.</p></div><button type="button" className={styles.button} disabled={disabled} onClick={onCancel}>Close editor</button></div>
  {stale?<div className={styles.notice} role="alert">A newer version is available. Your unsaved inputs are still here; copy anything you need before reloading. <button type="button" className={styles.button} disabled={disabled} onClick={onReload}>Discard edits and load latest</button></div>:null}
  {issue?<p className={styles.error} role="alert">{issue}</p>:null}
  <fieldset disabled={disabled}><div className={styles.split}><label className={styles.field}>Title<input required maxLength={200} value={fields.title} onChange={e=>set('title',e.target.value)}/></label><label className={styles.field}>Working stage<select value={fields.stage} onChange={e=>set('stage',e.target.value as 'idea'|'draft')}><option value="idea">Idea</option><option value="draft">Draft</option></select></label></div>
  <div className={styles.split}><label className={styles.field}>Purpose<textarea maxLength={2000} value={fields.purpose} onChange={e=>set('purpose',e.target.value)}/></label><label className={styles.field}>Audience<textarea maxLength={1000} value={fields.audience} onChange={e=>set('audience',e.target.value)}/></label></div>
  <div className={styles.split}><MemberSelect members={members} value={fields.owner_id} onChange={v=>set('owner_id',v)} required/><MemberSelect members={members} value={fields.reply_owner_id} onChange={v=>set('reply_owner_id',v)} heading="Reply responsibility"/></div>
  <div className={styles.split}><label className={styles.field}>Channel<select value={fields.channel} onChange={e=>set('channel',e.target.value as Channel)}>{['instagram','tiktok','linkedin','youtube','pinterest','other'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className={styles.field}>Destination account label<input maxLength={160} required value={fields.account_label} onChange={e=>set('account_label',e.target.value)} placeholder="Exact account or handle"/></label></div>
  <label className={styles.field}>Format<select value={fields.format} onChange={e=>set('format',e.target.value as DraftFields['format'])}>{['post','story','reel','video'].map(value=><option key={value} value={value}>{value}</option>)}</select></label>
  <label className={styles.field}>Public caption<textarea rows={7} maxLength={10000} value={fields.caption} onChange={e=>set('caption',e.target.value)}/><small>This exact caption will be reviewed for publication. Keep private strategy and source notes out.</small></label>
  <div className={styles.split}><SourcePicker workspaceId={workspaceId} kind="ideas" value={fields.idea_id} onChange={v=>set('idea_id',v)} disabled={disabled}/><SourcePicker workspaceId={workspaceId} kind="projects" value={fields.project_id} onChange={v=>{setFields(old=>({...old,project_id:v,source_version_id:''}));onDirty(true);}} disabled={disabled}/></div>
  <SourcePicker workspaceId={workspaceId} kind="versions" value={fields.source_version_id} projectId={fields.project_id} onChange={v=>set('source_version_id',v)} onSelected={v=>{setFields(old=>({...old,project_id:v.project_id}));}} disabled={disabled}/>
  <div className={styles.notice}>Before review, select an exact creative-approved source version. Creative approval only makes media eligible; all named reviewers must separately approve this publication package.</div>
  <label className={styles.field}>IANA timezone<input value={fields.timezone} required maxLength={100} onChange={e=>set('timezone',e.target.value)} placeholder="Europe/London"/><small>All date/time fields below use this timezone. Changing it keeps the entered clock times and changes their absolute times.</small></label>
  <div className={styles.split}><label className={styles.field}>Planned posting time<input type="datetime-local" value={fields.planned_at} onChange={e=>set('planned_at',e.target.value)}/><small>Planning only. No automatic scheduling or posting.</small></label><label className={styles.field}>Embargo ends<input type="datetime-local" value={fields.embargo_until} onChange={e=>set('embargo_until',e.target.value)}/></label></div>
  <label className={styles.field}>Internal release constraints<textarea maxLength={2000} value={fields.release_note} onChange={e=>set('release_note',e.target.value)}/><small>Reviewers see these constraints. Private release notes are excluded from the downloadable public package.</small></label>
  <h3>Exact media versions and public clearance</h3><p className={styles.muted}>An upload or workspace link does not establish publication rights. Record rights, consent and any public attribution for each selected item.</p>
  {fields.assets.map((item,index)=><section className={styles.asset} key={index}><div className={styles.spread}><h3>Media {index+1}</h3><button type="button" className={styles.danger} onClick={()=>set('assets',fields.assets.filter((_,i)=>i!==index))}>Remove media {index+1}</button></div><SourcePicker workspaceId={workspaceId} kind="versions" value={item.version_id} onChange={id=>asset(index,{version_id:id})} disabled={disabled} approvedOnly/>
   <label className={styles.field}>Publication rights<select value={item.rights} onChange={e=>asset(index,{rights:e.target.value as AssetClearance['rights']})}><option value="owned">Owned and cleared for publication</option><option value="licensed">Licensed and permitted for publication</option><option value="link_only">External link only, no download rights</option></select></label>
   <label className={styles.field}>Internal rights evidence / license notes<textarea maxLength={2000} value={item.rights_note} onChange={e=>asset(index,{rights_note:e.target.value})}/><small>Keep rights evidence here. It is excluded from the public package.</small></label>
   <label className={styles.checkbox}><input type="checkbox" checked={item.consent_confirmed} onChange={e=>asset(index,{consent_confirmed:e.target.checked})}/>Required permissions and consent are confirmed for this exact version.</label>
   <label className={styles.field}>Public attribution<input maxLength={1000} value={item.attribution} onChange={e=>asset(index,{attribution:e.target.value})}/><small>This text appears in the publication package. Use only publication-safe credit.</small></label>
   <label className={styles.field}>Permitted public HTTPS link<input type="url" value={item.public_link||''} onChange={e=>asset(index,{public_link:e.target.value||null})} placeholder="https://…"/><small>Required for link-only media. Never enter a private signed download URL or confidential source.</small></label>
  </section>)}
  <button type="button" className={styles.button} disabled={fields.assets.length>=20} onClick={()=>set('assets',[...fields.assets,{version_id:'',rights:'owned',rights_note:'',consent_confirmed:false,attribution:'',public_link:null}])}>Add exact media version</button>
  <div className={styles.toolbar}><button type="submit" className={styles.primary} disabled={Boolean(stale)}>Save {fields.stage}</button><button type="button" className={styles.button} onClick={onCancel}>Cancel</button></div></fieldset>
 </form>;
}
