'use client';
import { useState } from 'react';
import type { SocialDetail, SocialSnapshot } from '../../../lib/studio/social/contracts';
import { instantFromWall, readSocialManifest, safeSocialUrl, socialAssetUrl, socialPackageUrl } from '../../../lib/studio/social/client';
import { dateLabel, type MutationController } from './ui';
import styles from './social.module.css';
export function ManualPackage({workspaceId,snapshot,disabled}:{workspaceId:string;snapshot:SocialSnapshot;disabled:boolean}) {
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function copy(){if(busy||disabled)return;setBusy(true);setError('');setStatus('');try{const manifest=await readSocialManifest(workspaceId,snapshot.id);if(!navigator.clipboard)throw new Error('Clipboard access is unavailable. Select and copy the approved caption below.');await navigator.clipboard.writeText(manifest.caption);setStatus('Approved caption copied.');}catch(cause){setError(cause instanceof Error?cause.message:'The caption could not be copied.');}finally{setBusy(false);}}
 const p=snapshot.payload;
 const embargoed=Boolean(p.embargo_until&&new Date(p.embargo_until).getTime()>Date.now());
 const unavailable=disabled||embargoed;
 return <section className={styles.panel}><h2>Manual publication package</h2><p className={styles.muted}>Approved snapshot {snapshot.ordinal} · {p.channel} · {p.account_label} · {p.format}<br/>Planned {dateLabel(p.planned_at,p.timezone)} ({p.timezone})<br/>Embargo {p.embargo_until?dateLabel(p.embargo_until,p.timezone):'None recorded'}</p><p className={styles.notice}>Download permitted assets and the approval manifest, then publish manually in the destination account. This does not schedule or post anything.</p>{embargoed?<p className={styles.notice}>This package is embargoed. Refresh after the release time to download or copy it.</p>:null}<div className={styles.caption}>{p.caption}</div><div className={styles.toolbar}><button className={styles.button} disabled={unavailable||busy} onClick={()=>void copy()}>{busy?'Checking approved caption…':'Copy approved caption'}</button>{!unavailable?<a className={styles.button} href={socialPackageUrl(workspaceId,snapshot.id)} download>Download approval manifest</a>:null}</div>{status?<p className={styles.success} role="status">{status}</p>:null}{error?<p className={styles.error} role="alert">{error}</p>:null}<ul className={styles.list}>{p.assets.map((asset,index)=><li key={`${asset.version_id}-${index}`}><h3>Media {index+1}</h3><p className={styles.muted}>Public credit: {asset.attribution||'None specified'}</p>{asset.rights==='link_only'?<><p className={styles.small}>External reference only. No owned download rights; Fairway does not fetch or repackage this media.</p>{safeSocialUrl(asset.public_link)&&!unavailable?<a className={styles.link} href={safeSocialUrl(asset.public_link)!} rel="noopener noreferrer" target="_blank">Open permitted public reference</a>:null}</>:!unavailable?<a className={styles.button} href={socialAssetUrl(workspaceId,snapshot.id,index)} download>Download approved media {index+1}</a>:null}</li>)}</ul></section>;
}
export function PublicationForm({detail,snapshot,mutation,disabled,onDirty,onCancel}:{detail:SocialDetail;snapshot:SocialSnapshot;mutation:MutationController;disabled:boolean;onDirty:(value:boolean)=>void;onCancel:()=>void}) {
 const [url,setUrl]=useState(''),[time,setTime]=useState(''),[issue,setIssue]=useState('');
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();setIssue('');try{const safe=safeSocialUrl(url);if(!safe)throw new Error('Enter the public HTTPS post URL without embedded credentials.');const posted=instantFromWall(time,snapshot.payload.timezone);if(!posted)throw new Error('Enter the actual posting time.');mutation.mutate('recordPublication',{post_id:detail.post.id,expected_revision:detail.post.revision,snapshot_id:snapshot.id,url:safe,posted_at:posted},'Publication saved as manually recorded, not platform-verified.',()=>{onDirty(false);onCancel();});}catch(cause){setIssue(cause instanceof Error?cause.message:'Check the publication details.');}}}><h2>Mark snapshot {snapshot.ordinal} as posted</h2><p className={styles.muted}>Record a post you already published manually. This fact is team-entered and is not verified by the platform.</p>{issue?<p className={styles.error} role="alert">{issue}</p>:null}<fieldset disabled={disabled}><label className={styles.field}>Actual public post URL<input type="url" required value={url} onChange={e=>{setUrl(e.target.value);onDirty(true);}}/></label><label className={styles.field}>Actual posting time ({snapshot.payload.timezone})<input type="datetime-local" required value={time} onChange={e=>{setTime(e.target.value);onDirty(true);}}/></label><div className={styles.toolbar}><button className={styles.primary}>Record manual publication</button><button type="button" className={styles.button} onClick={onCancel}>Cancel</button></div></fieldset></form>;
}
