'use client';
import { useState } from 'react';
import type { SocialDetail, SocialMember, SocialReview, SocialSnapshot } from '../../../lib/studio/social/contracts';
import { safeSocialUrl } from '../../../lib/studio/social/client';
import { Badge, dateLabel, memberName, stateLabel, type MutationController } from './ui';
import styles from './social.module.css';
export function SnapshotContent({snapshot,members,onOpenFile}:{snapshot:SocialSnapshot;members:SocialMember[];onOpenFile?:(id:string)=>void}) {
 const p=snapshot.payload;
 return <div className={styles.stack}><div className={styles.row}><Badge>Snapshot {snapshot.ordinal}</Badge><span className={styles.small}>From draft revision {snapshot.draft_revision} · {dateLabel(snapshot.created_at)}</span></div><h3>{p.title}</h3><p className={styles.muted}>{p.channel} · {p.account_label} · {p.format}<br/>Planned {dateLabel(p.planned_at,p.timezone)} ({p.timezone})<br/>Embargo {p.embargo_until?dateLabel(p.embargo_until,p.timezone):'None recorded'}<br/>Owner {memberName(members,p.owner_id)} · Replies {memberName(members,p.reply_owner_id)}</p><div className={styles.caption}>{p.caption||'No caption'}</div><p className={styles.small}>Exact source version: {p.source_version_id||'Not selected'}</p><p className={styles.prose}>Purpose: {p.purpose||'Not recorded'}<br/>Audience: {p.audience||'Not recorded'}<br/>Internal release constraints: {p.release_note||'None recorded'}</p><ul className={styles.list}>{p.assets.map((asset,index)=><li key={`${asset.version_id}-${index}`}><strong>Media {index+1}</strong>{asset.rights==='link_only'?(safeSocialUrl(asset.public_link)?<a className={styles.link} href={safeSocialUrl(asset.public_link)!} target="_blank" rel="noopener noreferrer">Inspect permitted public reference {index+1}</a>:<p className={styles.small}>No valid public reference available.</p>):<a className={styles.link} href={`/api/studio/media?${new URLSearchParams({versionId:asset.version_id})}`} target="_blank" rel="noopener noreferrer">Inspect exact media version {index+1}</a>}{onOpenFile&&typeof (asset as {file_id?:string}).file_id==='string'?<button type="button" className={styles.button} onClick={()=>onOpenFile((asset as {file_id?:string}).file_id!)}>Open source file in Library</button>:null}<p className={styles.small}>Version {asset.version_id}</p><p className={styles.prose}>Rights: {asset.rights}<br/>Rights evidence: {asset.rights_note||'Not recorded'}<br/>Consent: {asset.consent_confirmed?'Confirmed':'Not confirmed'}<br/>Public attribution: {asset.attribution||'None'}<br/>Public link: {asset.public_link||'None'}</p></li>)}</ul></div>;
}
export function ReviewSubmit({detail,members,mutation,disabled,onDirty,onCancel}:{detail:SocialDetail;members:SocialMember[];mutation:MutationController;disabled:boolean;onDirty:(dirty:boolean)=>void;onCancel:()=>void}) {
 const [reviewers,setReviewers]=useState<string[]>([]),[error,setError]=useState('');
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();if(!reviewers.length){setError('Choose at least one named current reviewer.');return;}mutation.mutate('submitReview',{post_id:detail.post.id,expected_revision:detail.post.revision,reviewers},'Immutable publication package submitted for all named reviewers.',()=>{onDirty(false);onCancel();});}}><h2>Request publication review</h2><p className={styles.muted}>Submitting freezes the exact caption, media versions, destination, timing, embargo and clearances. Every named reviewer must approve this snapshot. Creative approval alone cannot approve public posting.</p>{error?<p className={styles.error} role="alert">{error}</p>:null}<fieldset disabled={disabled}><legend>All of these reviewers must approve</legend>{members.map(member=><label className={styles.checkbox} key={member.id}><input type="checkbox" checked={reviewers.includes(member.id)} onChange={e=>{setReviewers(old=>e.target.checked?[...old,member.id]:old.filter(id=>id!==member.id));onDirty(true);}}/>{memberName(members,member.id)}</label>)}{(!detail.post.source_version_id||!detail.post.planned_at||!detail.post.caption.trim())?<p className={styles.notice}>Before submitting, save a caption, planned posting time and creative-approved exact source version.</p>:null}<div className={styles.toolbar}><button className={styles.primary} disabled={!reviewers.length||!detail.post.source_version_id||!detail.post.planned_at||!detail.post.caption.trim()}>Submit exact package</button><button type="button" className={styles.button} onClick={onCancel}>Cancel</button></div></fieldset></form>;
}
export function ReviewDecision({detail,snapshot,review,members,mutation,disabled,onDirty,onCancel}:{detail:SocialDetail;snapshot:SocialSnapshot;review:SocialReview;members:SocialMember[];mutation:MutationController;disabled:boolean;onDirty:(dirty:boolean)=>void;onCancel:()=>void}) {
 const [note,setNote]=useState(''),[disposition,setDisposition]=useState<'approve'|'request_changes'>('approve');
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();mutation.mutate('decideReview',{post_id:detail.post.id,snapshot_id:snapshot.id,expected_review_revision:review.revision,disposition,note},disposition==='approve'?'Your explicit publication approval was recorded.':'Your change request was recorded.',()=>{onDirty(false);onCancel();});}}><h2>Review exact snapshot {snapshot.ordinal}</h2><SnapshotContent snapshot={snapshot} members={members}/><fieldset disabled={disabled}><label className={styles.field}>Your decision<select value={disposition} onChange={e=>{setDisposition(e.target.value as typeof disposition);onDirty(true);}}><option value="approve">Approve this exact package for manual publication</option><option value="request_changes">Request changes</option></select></label><label className={styles.field}>Review note<textarea maxLength={2000} required={disposition==='request_changes'} value={note} onChange={e=>{setNote(e.target.value);onDirty(true);}}/></label><p className={styles.muted}>Your decision applies only to this immutable package. It does not post content or change creative approvals.</p><div className={styles.toolbar}><button className={styles.primary}>Record my decision</button><button type="button" className={styles.button} onClick={onCancel}>Cancel</button></div></fieldset></form>;
}
export function SnapshotHistory({detail,members,onOpenFile}:{detail:SocialDetail;members:SocialMember[];onOpenFile?:(id:string)=>void}) {
 return <section className={styles.panel}><h2>Immutable review history</h2>{!detail.snapshots.length?<p className={styles.muted}>No publication snapshots yet. Saving a draft does not approve it.</p>:detail.snapshots.map(snapshot=>{const review=detail.reviews.find(r=>r.snapshot_id===snapshot.id);return <details key={snapshot.id} className={styles.asset}><summary>Snapshot {snapshot.ordinal} · {review?stateLabel(review.state):'Review unavailable'}{detail.post.approved_snapshot_id===snapshot.id?(['approved','posted'].includes(detail.post.state)?' · current approved package':' · previously approved package'):''}</summary><SnapshotContent snapshot={snapshot} members={members} onOpenFile={onOpenFile}/><h3>All named reviewers</h3><ul className={styles.list}>{snapshot.reviewers.map(id=>{const decision=detail.decisions.filter(d=>d.snapshot_id===snapshot.id&&d.reviewer_id===id).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];return <li key={id}><strong>{memberName(members,id)}</strong><p className={styles.muted}>{decision?`${decision.disposition==='approve'?'Approved':'Changes requested'} · ${dateLabel(decision.created_at)}`:'Awaiting explicit decision'}</p>{decision?.note?<p className={styles.prose}>{decision.note}</p>:null}</li>;})}</ul></details>;})}</section>;
}
