'use client';
import { useEffect, useState } from 'react';
import type { SocialOptions } from '../../../lib/studio/social/contracts';
import { asSocialError, readSocialOptions, type SocialApiError } from '../../../lib/studio/social/client';
import { ErrorState } from './ui';
import styles from './social.module.css';
export function SourcePicker({workspaceId,kind,value,onChange,disabled=false,approvedOnly=false,projectId,onSelected}:{workspaceId:string;kind:keyof SocialOptions;value:string;onChange:(id:string)=>void;disabled?:boolean;approvedOnly?:boolean;projectId?:string|null;onSelected?:(option:SocialOptions['versions'][number])=>void}) {
 const [query,setQuery]=useState(''),[page,setPage]=useState(0),[options,setOptions]=useState<SocialOptions|null>(null),[error,setError]=useState<SocialApiError|null>(null),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 const [known,setKnown]=useState<Record<string,string>>({});
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError(null);const timer=setTimeout(()=>{void readSocialOptions(workspaceId,query,page,controller.signal).then(data=>{if(controller.signal.aborted)return;setOptions(data);setKnown(old=>({...old,...Object.fromEntries(data[kind].map(o=>[o.id,o.title]))}));}).catch(cause=>{if(!controller.signal.aborted){setError(asSocialError(cause));setOptions(null);}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);controller.abort();};},[workspaceId,query,page,kind,refresh]);
 const available=options?.[kind].filter(option=>kind!=='versions'||(!approvedOnly||((option as SocialOptions['versions'][number]).creative_approved&&Boolean((option as SocialOptions['versions'][number]).file_id)))&&(!projectId||(option as SocialOptions['versions'][number]).project_id===projectId))||[];
 const heading=kind==='ideas'?'Canonical idea':kind==='projects'?'Source project':'Exact creative version';
 return <div className={styles.stack}><label className={styles.field}>Search {heading.toLowerCase()}<input type="search" maxLength={200} value={query} disabled={disabled} placeholder="Search permitted source titles" onChange={e=>{setQuery(e.target.value);setPage(0);}} /></label><label className={styles.field}>{heading}<select value={value} disabled={disabled||loading||Boolean(error)} onChange={e=>{onChange(e.target.value);const selected=options?.versions.find(o=>o.id===e.target.value);if(selected)onSelected?.(selected);}}><option value="">Not linked</option>{value&&!available.some(o=>o.id===value)?<option value={value}>{known[value]||`Selected version or record · …${value.slice(-8)}`}</option>:null}{available.map(option=><option key={option.id} value={option.id}>{option.title}{kind==='versions'?(option as SocialOptions['versions'][number]).creative_approved?' · creative approved':' · not creative approved':''}</option>)}</select><small>{approvedOnly?'Only creative-approved media versions are eligible. Public rights and separate publication approval are still required.':'Titles only. Source notes and bodies are never copied into a publication package.'}</small></label>{loading?<p className={styles.small} role="status">Loading source choices…</p>:null}{error?<ErrorState error={error} retry={()=>setRefresh(v=>v+1)}/>:null}<div className={styles.row}><button type="button" className={styles.button} disabled={disabled||loading||page===0} onClick={()=>setPage(p=>p-1)}>Previous choices</button><span className={styles.small}>Page {page+1}</span><button type="button" className={styles.button} disabled={disabled||loading||Boolean(error)||!options||![options.ideas.length,options.projects.length,options.versions.length].some(length=>length===50)} onClick={()=>setPage(p=>p+1)}>More choices</button></div></div>;
}
