import {StudioError} from '@/lib/studio/contracts';
import {validatePrivateMutation} from '@/lib/studio/private-business/contracts';
import {readPrivateBusiness,mutatePrivateBusiness} from '@/lib/studio/private-business/server';
import {isSameOriginWrite} from '@/lib/studio/request-origin';
export const dynamic='force-dynamic';
const headers={'Cache-Control':'private, no-store, max-age=0','Pragma':'no-cache','Vary':'Cookie','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};
function failure(error:unknown){const known=error instanceof StudioError?error:new StudioError('Private records are temporarily unavailable.','INTERNAL',500);return Response.json({error:known.message,code:known.code},{status:known.status,headers});}
export async function GET(request:Request){try{const params=new URL(request.url).searchParams;if(params.get("q"))throw new StudioError("Send private searches in the POST body.","VALIDATION",422);return Response.json(await readPrivateBusiness(params),{headers})}catch(error){return failure(error)}}
export async function POST(request:Request){try{if(!isSameOriginWrite(request)||request.headers.get('sec-fetch-site')==='cross-site')throw new StudioError('Cross-site writes are not allowed.','FORBIDDEN',403);if(Number(request.headers.get('content-length')??0)>30000)throw new StudioError('Request too large.','VALIDATION',413);const raw=await request.text();if(new TextEncoder().encode(raw).byteLength>30000)throw new StudioError('Request too large.','VALIDATION',413);let value:unknown;try{value=JSON.parse(raw)}catch{throw new StudioError('Valid JSON required.','VALIDATION',422)}if(value&&typeof value==='object'&&!Array.isArray(value)&&'action' in value){const body=value as Record<string,unknown>;if(body.action!=='read'||Object.keys(body).some(k=>!['action','workspaceId','expectedUserId','bookId','recordId','kind','page','query','options'].includes(k)))throw new StudioError('Invalid read request.','VALIDATION',422);const params=new URLSearchParams();for(const [key,v] of Object.entries(body)){if(key==='action'||v===null||v===undefined)continue;if(typeof v!=='string'&&!(key==='page'&&Number.isSafeInteger(v)))throw new StudioError('Invalid read field.','VALIDATION',422);params.set(key==='query'?'q':key,String(v));}return Response.json(await readPrivateBusiness(params),{headers});}return Response.json({data:await mutatePrivateBusiness(validatePrivateMutation(value))},{headers})}catch(error){return failure(error)}}
