import type { WorkflowRoute } from '@/lib/studio/workflows/routes';
import styles from './workflows.module.css';
/** Static, opt-in guidance. Never reads record content, starts an AI call or changes a record. */
export function WorkflowHelp({route}: {route: WorkflowRoute}) {
 const content = route.kind === 'content';
 const privateView = route.kind === 'private';
 return <details className={styles.help}><summary>{content ? 'How content planning works' : privateView ? 'How restricted registers work' : 'How Business plans work'}</summary>
 {content ? <><p>Capture an idea, choose the exact cleared creative media, add your caption and destination, then ask named people to review the publication package. Creative approval alone does not approve a public post.</p><p>After approval, use the manual package and record the actual post yourself. Calendar dates are plans. Feedback and metrics are entered by a person; missing metrics stay unknown. Nothing is automatically posted, scheduled or sent to an AI service.</p></> : privateView ? <><p>A restricted register contains documents, contracts and manually entered financial records. Its creator, current workspace owners and specifically granted members can access it. Sharing a register includes its whole current and historical contents. Record ownership alone does not grant access.</p><p>Document uploads and app-served document downloads are unavailable. You can save versioned HTTPS references; the external provider controls their access and contents. Marked signed is a manually recorded fact, and budget approval is planning only. No payment or signature is executed.</p><p>Private data stays within this restricted area. Do not copy sensitive contract or financial details into workspace-visible plans, task titles or content drafts. Views and unsaved forms clear when backgrounded; save first. Resolve an unconfirmed save with the exact retry before leaving.</p></> : <><p>Capture a draft or idea and develop the same record into a plan. Connect owners, SWOT responses, canonical tasks and permitted supporting files. Changes to a task appear in both Business and Tasks.</p><p>Submit an exact snapshot to named reviewers. All reviewers must explicitly approve it. Later edits keep the previous final unchanged and require a new review. Approval does not authorize spending, contracting or publication.</p><p>Plans are workspace-visible. Use Documents & Contracts or Budget & Finance for restricted information. These sections enforce their own access and never copy private records into a plan.</p></>}
 </details>;
}
export function BusinessSubnav({base,route,onNavigate}:{base:string;route:WorkflowRoute;onNavigate:(url:string)=>boolean}) {
 return <nav className={styles.nav} aria-label="Business sections">{[{label:'Drafts & Plans',url:`${base}/business`,active:route.kind==='plans'}, {label:'Documents & Contracts',url:`${base}/business/documents`,active:route.kind==='private'&&route.tab==='documents'}, {label:'Budget & Finance',url:`${base}/business/finance`,active:route.kind==='private'&&route.tab==='finance'}].map(item=><a key={item.url} href={item.url} aria-current={item.active?'page':undefined} onClick={event=>{event.preventDefault();onNavigate(item.url);}}>{item.label}</a>)}</nav>;
}
